//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MotorClaimServices.wsMC {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MotorClaimWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class MotorClaimWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SendMotorClaimOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendConsentFormOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MotorClaimWebService() {
            this.Url = global::MotorClaimServices.Properties.Settings.Default.MotorClaimServices_wsMC_MotorClaimWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SendMotorClaimCompletedEventHandler SendMotorClaimCompleted;
        
        /// <remarks/>
        public event SendConsentFormCompletedEventHandler SendConsentFormCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendMotorClaim", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ClaimTransaction_Data_Result[] SendMotorClaim(string _UWCode, string _Password, ClaimTransaction_Data[] _Data) {
            object[] results = this.Invoke("SendMotorClaim", new object[] {
                        _UWCode,
                        _Password,
                        _Data});
            return ((ClaimTransaction_Data_Result[])(results[0]));
        }
        
        /// <remarks/>
        public void SendMotorClaimAsync(string _UWCode, string _Password, ClaimTransaction_Data[] _Data) {
            this.SendMotorClaimAsync(_UWCode, _Password, _Data, null);
        }
        
        /// <remarks/>
        public void SendMotorClaimAsync(string _UWCode, string _Password, ClaimTransaction_Data[] _Data, object userState) {
            if ((this.SendMotorClaimOperationCompleted == null)) {
                this.SendMotorClaimOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMotorClaimOperationCompleted);
            }
            this.InvokeAsync("SendMotorClaim", new object[] {
                        _UWCode,
                        _Password,
                        _Data}, this.SendMotorClaimOperationCompleted, userState);
        }
        
        private void OnSendMotorClaimOperationCompleted(object arg) {
            if ((this.SendMotorClaimCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMotorClaimCompleted(this, new SendMotorClaimCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendConsentForm", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ClaimTransaction_Data_Result[] SendConsentForm(string _UWCode, string _Password, ClaimTransaction_ConsentForm[] _Data) {
            object[] results = this.Invoke("SendConsentForm", new object[] {
                        _UWCode,
                        _Password,
                        _Data});
            return ((ClaimTransaction_Data_Result[])(results[0]));
        }
        
        /// <remarks/>
        public void SendConsentFormAsync(string _UWCode, string _Password, ClaimTransaction_ConsentForm[] _Data) {
            this.SendConsentFormAsync(_UWCode, _Password, _Data, null);
        }
        
        /// <remarks/>
        public void SendConsentFormAsync(string _UWCode, string _Password, ClaimTransaction_ConsentForm[] _Data, object userState) {
            if ((this.SendConsentFormOperationCompleted == null)) {
                this.SendConsentFormOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendConsentFormOperationCompleted);
            }
            this.InvokeAsync("SendConsentForm", new object[] {
                        _UWCode,
                        _Password,
                        _Data}, this.SendConsentFormOperationCompleted, userState);
        }
        
        private void OnSendConsentFormOperationCompleted(object arg) {
            if ((this.SendConsentFormCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendConsentFormCompleted(this, new SendConsentFormCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ClaimTransaction_Data {
        
        private string claimStatusField;
        
        private string tempPolicyField;
        
        private string refNoField;
        
        private int versionField;
        
        private string policyNoField;
        
        private int policyYearField;
        
        private string claimNoField;
        
        private string transactionDateField;
        
        private string unwriterField;
        
        private string insuredNameField;
        
        private string effectiveDateField;
        
        private string expiryDateField;
        
        private string beneficiaryField;
        
        private string carBrandField;
        
        private string carModelField;
        
        private string carLicenseField;
        
        private string carYearField;
        
        private string chassisNoField;
        
        private string showRoomNameField;
        
        private string showRoomCodeField;
        
        private string claimNoticeDateField;
        
        private string claimNoticeTimeField;
        
        private string claimDetailsField;
        
        private int claimTypeField;
        
        private int claimResultField;
        
        private string claimDamageDetailsField;
        
        private string callCenterField;
        
        private string accidentDateField;
        
        private string accidentTimeField;
        
        private string accidentPlaceField;
        
        private string accidentTumbonField;
        
        private string accidentAmphurField;
        
        private string accidentProvinceField;
        
        private string accidentZipcodeField;
        
        private string driverNameField;
        
        private string driverTelField;
        
        private string noticeNameField;
        
        private string noticeTelField;
        
        private int garageTypeField;
        
        private string garageCodeField;
        
        private string garageNameField;
        
        private string garagePlaceField;
        
        private string garageTumbonField;
        
        private string garageAmphurField;
        
        private string garageProvinceField;
        
        private string garageZipcodeField;
        
        private string carRepairDateField;
        
        private string carReceiveDateField;
        
        private string consentFormNoField;
        
        private string partsDealerNameField;
        
        private string paymentDetailsField;
        
        private double amount1Field;
        
        private double amount2Field;
        
        private double amount3Field;
        
        private string remarkField;
        
        /// <remarks/>
        public string ClaimStatus {
            get {
                return this.claimStatusField;
            }
            set {
                this.claimStatusField = value;
            }
        }
        
        /// <remarks/>
        public string TempPolicy {
            get {
                return this.tempPolicyField;
            }
            set {
                this.tempPolicyField = value;
            }
        }
        
        /// <remarks/>
        public string RefNo {
            get {
                return this.refNoField;
            }
            set {
                this.refNoField = value;
            }
        }
        
        /// <remarks/>
        public int Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public string PolicyNo {
            get {
                return this.policyNoField;
            }
            set {
                this.policyNoField = value;
            }
        }
        
        /// <remarks/>
        public int PolicyYear {
            get {
                return this.policyYearField;
            }
            set {
                this.policyYearField = value;
            }
        }
        
        /// <remarks/>
        public string ClaimNo {
            get {
                return this.claimNoField;
            }
            set {
                this.claimNoField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionDate {
            get {
                return this.transactionDateField;
            }
            set {
                this.transactionDateField = value;
            }
        }
        
        /// <remarks/>
        public string Unwriter {
            get {
                return this.unwriterField;
            }
            set {
                this.unwriterField = value;
            }
        }
        
        /// <remarks/>
        public string InsuredName {
            get {
                return this.insuredNameField;
            }
            set {
                this.insuredNameField = value;
            }
        }
        
        /// <remarks/>
        public string EffectiveDate {
            get {
                return this.effectiveDateField;
            }
            set {
                this.effectiveDateField = value;
            }
        }
        
        /// <remarks/>
        public string ExpiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
            }
        }
        
        /// <remarks/>
        public string Beneficiary {
            get {
                return this.beneficiaryField;
            }
            set {
                this.beneficiaryField = value;
            }
        }
        
        /// <remarks/>
        public string CarBrand {
            get {
                return this.carBrandField;
            }
            set {
                this.carBrandField = value;
            }
        }
        
        /// <remarks/>
        public string CarModel {
            get {
                return this.carModelField;
            }
            set {
                this.carModelField = value;
            }
        }
        
        /// <remarks/>
        public string CarLicense {
            get {
                return this.carLicenseField;
            }
            set {
                this.carLicenseField = value;
            }
        }
        
        /// <remarks/>
        public string CarYear {
            get {
                return this.carYearField;
            }
            set {
                this.carYearField = value;
            }
        }
        
        /// <remarks/>
        public string ChassisNo {
            get {
                return this.chassisNoField;
            }
            set {
                this.chassisNoField = value;
            }
        }
        
        /// <remarks/>
        public string ShowRoomName {
            get {
                return this.showRoomNameField;
            }
            set {
                this.showRoomNameField = value;
            }
        }
        
        /// <remarks/>
        public string ShowRoomCode {
            get {
                return this.showRoomCodeField;
            }
            set {
                this.showRoomCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ClaimNoticeDate {
            get {
                return this.claimNoticeDateField;
            }
            set {
                this.claimNoticeDateField = value;
            }
        }
        
        /// <remarks/>
        public string ClaimNoticeTime {
            get {
                return this.claimNoticeTimeField;
            }
            set {
                this.claimNoticeTimeField = value;
            }
        }
        
        /// <remarks/>
        public string ClaimDetails {
            get {
                return this.claimDetailsField;
            }
            set {
                this.claimDetailsField = value;
            }
        }
        
        /// <remarks/>
        public int ClaimType {
            get {
                return this.claimTypeField;
            }
            set {
                this.claimTypeField = value;
            }
        }
        
        /// <remarks/>
        public int ClaimResult {
            get {
                return this.claimResultField;
            }
            set {
                this.claimResultField = value;
            }
        }
        
        /// <remarks/>
        public string ClaimDamageDetails {
            get {
                return this.claimDamageDetailsField;
            }
            set {
                this.claimDamageDetailsField = value;
            }
        }
        
        /// <remarks/>
        public string CallCenter {
            get {
                return this.callCenterField;
            }
            set {
                this.callCenterField = value;
            }
        }
        
        /// <remarks/>
        public string AccidentDate {
            get {
                return this.accidentDateField;
            }
            set {
                this.accidentDateField = value;
            }
        }
        
        /// <remarks/>
        public string AccidentTime {
            get {
                return this.accidentTimeField;
            }
            set {
                this.accidentTimeField = value;
            }
        }
        
        /// <remarks/>
        public string AccidentPlace {
            get {
                return this.accidentPlaceField;
            }
            set {
                this.accidentPlaceField = value;
            }
        }
        
        /// <remarks/>
        public string AccidentTumbon {
            get {
                return this.accidentTumbonField;
            }
            set {
                this.accidentTumbonField = value;
            }
        }
        
        /// <remarks/>
        public string AccidentAmphur {
            get {
                return this.accidentAmphurField;
            }
            set {
                this.accidentAmphurField = value;
            }
        }
        
        /// <remarks/>
        public string AccidentProvince {
            get {
                return this.accidentProvinceField;
            }
            set {
                this.accidentProvinceField = value;
            }
        }
        
        /// <remarks/>
        public string AccidentZipcode {
            get {
                return this.accidentZipcodeField;
            }
            set {
                this.accidentZipcodeField = value;
            }
        }
        
        /// <remarks/>
        public string DriverName {
            get {
                return this.driverNameField;
            }
            set {
                this.driverNameField = value;
            }
        }
        
        /// <remarks/>
        public string DriverTel {
            get {
                return this.driverTelField;
            }
            set {
                this.driverTelField = value;
            }
        }
        
        /// <remarks/>
        public string NoticeName {
            get {
                return this.noticeNameField;
            }
            set {
                this.noticeNameField = value;
            }
        }
        
        /// <remarks/>
        public string NoticeTel {
            get {
                return this.noticeTelField;
            }
            set {
                this.noticeTelField = value;
            }
        }
        
        /// <remarks/>
        public int GarageType {
            get {
                return this.garageTypeField;
            }
            set {
                this.garageTypeField = value;
            }
        }
        
        /// <remarks/>
        public string GarageCode {
            get {
                return this.garageCodeField;
            }
            set {
                this.garageCodeField = value;
            }
        }
        
        /// <remarks/>
        public string GarageName {
            get {
                return this.garageNameField;
            }
            set {
                this.garageNameField = value;
            }
        }
        
        /// <remarks/>
        public string GaragePlace {
            get {
                return this.garagePlaceField;
            }
            set {
                this.garagePlaceField = value;
            }
        }
        
        /// <remarks/>
        public string GarageTumbon {
            get {
                return this.garageTumbonField;
            }
            set {
                this.garageTumbonField = value;
            }
        }
        
        /// <remarks/>
        public string GarageAmphur {
            get {
                return this.garageAmphurField;
            }
            set {
                this.garageAmphurField = value;
            }
        }
        
        /// <remarks/>
        public string GarageProvince {
            get {
                return this.garageProvinceField;
            }
            set {
                this.garageProvinceField = value;
            }
        }
        
        /// <remarks/>
        public string GarageZipcode {
            get {
                return this.garageZipcodeField;
            }
            set {
                this.garageZipcodeField = value;
            }
        }
        
        /// <remarks/>
        public string CarRepairDate {
            get {
                return this.carRepairDateField;
            }
            set {
                this.carRepairDateField = value;
            }
        }
        
        /// <remarks/>
        public string CarReceiveDate {
            get {
                return this.carReceiveDateField;
            }
            set {
                this.carReceiveDateField = value;
            }
        }
        
        /// <remarks/>
        public string ConsentFormNo {
            get {
                return this.consentFormNoField;
            }
            set {
                this.consentFormNoField = value;
            }
        }
        
        /// <remarks/>
        public string PartsDealerName {
            get {
                return this.partsDealerNameField;
            }
            set {
                this.partsDealerNameField = value;
            }
        }
        
        /// <remarks/>
        public string PaymentDetails {
            get {
                return this.paymentDetailsField;
            }
            set {
                this.paymentDetailsField = value;
            }
        }
        
        /// <remarks/>
        public double Amount1 {
            get {
                return this.amount1Field;
            }
            set {
                this.amount1Field = value;
            }
        }
        
        /// <remarks/>
        public double Amount2 {
            get {
                return this.amount2Field;
            }
            set {
                this.amount2Field = value;
            }
        }
        
        /// <remarks/>
        public double Amount3 {
            get {
                return this.amount3Field;
            }
            set {
                this.amount3Field = value;
            }
        }
        
        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ClaimTransaction_ConsentForm {
        
        private string consentFormNoField;
        
        private string consentFormFileTypeField;
        
        private byte[] consentFormDataField;
        
        /// <remarks/>
        public string ConsentFormNo {
            get {
                return this.consentFormNoField;
            }
            set {
                this.consentFormNoField = value;
            }
        }
        
        /// <remarks/>
        public string ConsentFormFileType {
            get {
                return this.consentFormFileTypeField;
            }
            set {
                this.consentFormFileTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ConsentFormData {
            get {
                return this.consentFormDataField;
            }
            set {
                this.consentFormDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ClaimResultMessage {
        
        private string resultCodeField;
        
        private string resultMessageField;
        
        /// <remarks/>
        public string ResultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ResultMessage {
            get {
                return this.resultMessageField;
            }
            set {
                this.resultMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ClaimTransaction_Data_Result {
        
        private string tRNoField;
        
        private string resultNoField;
        
        private bool resultStatusField;
        
        private ClaimResultMessage[] resultMessageField;
        
        private System.DateTime submitDateField;
        
        /// <remarks/>
        public string TRNo {
            get {
                return this.tRNoField;
            }
            set {
                this.tRNoField = value;
            }
        }
        
        /// <remarks/>
        public string ResultNo {
            get {
                return this.resultNoField;
            }
            set {
                this.resultNoField = value;
            }
        }
        
        /// <remarks/>
        public bool ResultStatus {
            get {
                return this.resultStatusField;
            }
            set {
                this.resultStatusField = value;
            }
        }
        
        /// <remarks/>
        public ClaimResultMessage[] ResultMessage {
            get {
                return this.resultMessageField;
            }
            set {
                this.resultMessageField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SubmitDate {
            get {
                return this.submitDateField;
            }
            set {
                this.submitDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void SendMotorClaimCompletedEventHandler(object sender, SendMotorClaimCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendMotorClaimCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendMotorClaimCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ClaimTransaction_Data_Result[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ClaimTransaction_Data_Result[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void SendConsentFormCompletedEventHandler(object sender, SendConsentFormCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendConsentFormCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendConsentFormCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ClaimTransaction_Data_Result[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ClaimTransaction_Data_Result[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591