<?xml version="1.0" encoding="utf-8"?><Database Name="Tidmaster" Class="DataClasses_TIDMotorDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=localhost;Initial Catalog=Tidmaster;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="TidmasterConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.MotorData" Member="MotorDatas">
    <Type Name="MotorData">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDCodeCRV" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NameConTract" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="IDCardConTract" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="BirthDateConTract" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="AddressConTract1" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="AddressConTract2" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="AddressConTract3" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="EmailConTract" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="OfficeWorkConTract" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="PositionConTract" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="WorkAddressConTract1" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="WorkAddressConTract2" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="WorkAddressConTract3" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="TelHomeConTract" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="TelMobileConTract" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="TelWorkConTract" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="FaxContract" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="NameClient" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="IDCardClient" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="BirthDateClient" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="AddressClient1" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="AddressClient2" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="AddressClient3" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="EmailClient" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="OfficeWorkClient" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="PositionClient" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="WorkAddressClient1" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="WorkAddressClient2" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="WorkAddressClient3" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="TelHomeClient" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="TelMobileClient" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="TelWorkClient" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="FaxClient" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="NameDoc" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="AddressDoc1" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="AddressDoc2" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="AddressDoc3" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="TelHomeDoc" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="TelMobileDoc" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="TelWorkDoc" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="FaxDoc" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CarBrand" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CarModel" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="EngineNo" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="BodyNo" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CC" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="IDCar" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CarReg" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ProvinceReg" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="SubAgent" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CarType" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="GarageType" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="OldCar" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CarGroup" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="InSureType" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Driver" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="OldDriverType1" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="OldDriverType2" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="NameDriver1" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="NameDriver2" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="OldDriver1" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="OldDriver2" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CarUseType" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CarPropType" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="TypePropCar" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Accessories" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="cboTPBIPerson" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="cboTPBITime" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="cboTPPD" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ODFund" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="FnTFund" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="FnTFund1" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ValueDriverRY011" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="PassengerRY011" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ValuePassengerRY011" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ValueDriverRY012" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="PassengerRY012" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ValuePassengerRY012" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DriverPassengerRY02" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ValueEveryoneRY02" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ValueDriverRY03" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ValueFirstOD" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ValueFirstTPPD" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DiscountGroup" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DiscountHistory" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DiscountOther" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="AddHistory" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Discountspacial" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Pre_Net" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Pre_Stamp" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Pre_Vat" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Pre_Sum" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Pre_DisCountspacial" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Pre_Sum_Dis" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="PreDateStart" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="PreDateEnd" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="PreIDCode" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="PreRegisCode" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DiscountSticker" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Stick_Net" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Stick_Stamp" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Stick_Vat" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Stick_Sum" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Stick_DisCountspacial" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Stick_Sum_Dis" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="StickDateStart" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="StickDateEnd" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="StickIDCard" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="StickNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="stickCarType" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="StickRegisCode" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="PayType" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="PayPeriod" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PayDetail" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="PayDateIn" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="NoteOther" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ChkContract" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ChkDoc" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="SendStickType" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Doctype" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ChkPay" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="PreDateStartConFirm" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="PreDateEndConFirm" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="StickDateStartConFirm" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="StickDateEndConFirm" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CompanyTemp" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CompanyCode" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CompanyName" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Address1" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Address2" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Address3" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="TelNumberCenter" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FaxNumberCenter" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MailCenter" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TelNumber" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="FaxNumber" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Contact1" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Mail1" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="ProductCode" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="InFormCode" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="NoteInsure1" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="NoteInsure2" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="NoteInsure3" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="NoteClient1" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="IDCodeFrom1" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="IDCodeFrom2" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="IDPlan" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="SourceFrom" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="PromiseNo" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ClientCode" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DateReviewAdd" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DateReviewSave" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DateReviewUp" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DateClosing" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DateConFirm" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ClosingDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ConfirmDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateUpdate" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="UserReviewAdd" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="UserReviewUp" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="UserClosing" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="UserConFirm" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="UserUpdate" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="UserReviewSave" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ChkStatus" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ChkData" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="IpCom" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NameReceive" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="IDCodeUserChk" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BpremiumS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NumberDN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="OldPreIDCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateCancel" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserCancel" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NoteCancel" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="PreReciveDate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PreSendDate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="StickReciveDate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="StickSendDate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CamPaign" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserModify" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateModify" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TypeOfClient" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ReceiveDate" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="TaxNumber" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="SubAgent1" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="SubAgent2" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="SubAgent3" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="SubAgent4" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="DateLapsed" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserLapsed" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NoteLapsed" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="NoteLapsedDesc" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DateCancelPolicy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserCancelPolicy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NoteCancelPolicy" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DateUpdateCF" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserUpdateCF" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SpecialNote1" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="SpecialNote2" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="SpecialNote3" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ClientGroup" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BankCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateCancelEndorse" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserCancelEndorse" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NoteCancelEndorse" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="BillType" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="BillDate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DiscGroupID" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="RenewCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DealerCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ChkAddOn" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IDPlanA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="StartDateA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EndDateA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PremiumA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="StampA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VatA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PremiumNetA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DiscountA" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PreA_Disc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PreA_Sum_Disc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DiscussionTrans" Member="DiscussionTrans">
    <Type Name="DiscussionTran">
      <Column Name="TransID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DiscGroupID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IDCodeData" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="DiscNote" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="UserRec" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateRec" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CompanyInsure" Member="CompanyInsures">
    <Type Name="CompanyInsure">
      <Column Name="CompanyCode" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CNShort2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CNShort1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CNShort" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="address1" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="address2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="address3" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TelNumberCenter" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FaxNumberCenter" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MailCenter" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TelNumber1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FaxNumber1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Contact1" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Mail1" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="TelNumber2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FaxNumber2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Contact2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Mail2" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TelNumber3" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FaxNumber3" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Contact3" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Mail3" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="HistoryInsurer" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Prominent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Hotline" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DateRec" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DateUp" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserRec" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserUp" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IpCom" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FileGarage" Type="System.String" DbType="NVarChar(90)" CanBeNull="true" />
      <Column Name="TaxNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.V_MotorEndorsement" Member="V_MotorEndorsements">
    <Type Name="V_MotorEndorsement">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="REFNO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Motor" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="ClientCode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IDCARD" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ClientName" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Address1" Type="System.String" DbType="NVarChar(767)" CanBeNull="true" />
      <Column Name="PhoneNumber1" Type="System.String" DbType="VarChar(1051)" CanBeNull="true" />
      <Column Name="ConTractName" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Address2" Type="System.String" DbType="NVarChar(767)" CanBeNull="true" />
      <Column Name="PhoneNumber2" Type="System.String" DbType="VarChar(1051)" CanBeNull="true" />
      <Column Name="PolicyNo" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="RNType" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="PolicyType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Suminsured" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Benefitialy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Model" Type="System.String" DbType="NVarChar(511)" CanBeNull="true" />
      <Column Name="CarPlate" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CHASSIS" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CarEngine" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CMI_PolicyNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CMI_StickerNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CMI_StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CMI_EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Project" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Dealer" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="InsurerCode" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DriverName1" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DriverOld1" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DriverName2" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DriverOld2" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CarAccessories" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="CMI_PaymentBy" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="REFNOOld" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MotorOld" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="ClientCodeOld" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IDCARDOld" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ClientNameOld" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Address1Old" Type="System.String" DbType="NVarChar(767)" CanBeNull="true" />
      <Column Name="PhoneNumber1Old" Type="System.String" DbType="VarChar(1049)" CanBeNull="true" />
      <Column Name="ConTractNameOld" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Address2Old" Type="System.String" DbType="NVarChar(767)" CanBeNull="true" />
      <Column Name="PhoneNumber2Old" Type="System.String" DbType="VarChar(1049)" CanBeNull="true" />
      <Column Name="PolicyNoOld" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="StartDateOld" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDateOld" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="StatusOld" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="RNTypeOld" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="PolicyTypeOld" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SuminsuredOld" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="BenefitialyOld" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModelOld" Type="System.String" DbType="NVarChar(511)" CanBeNull="true" />
      <Column Name="CarPlateOld" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CHASSISOld" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CarEngineOld" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CMI_PolicyNoOld" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CMI_StickerNoOld" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CMI_StartDateOld" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CMI_EndDateOld" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ProjectOld" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DealerOld" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="InsurerCodeOld" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DriverName1Old" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="DriverOld1Old" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="DriverName2Old" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="DriverOld2Old" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="CMI_PaymentByOld" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.SP_APPLICATION_SEARCH" Method="SP_APPLICATION_SEARCH">
    <Parameter Name="IDCodeCRV" Parameter="iDCodeCRV" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="SP_APPLICATION_SEARCHResult">
      <Column Name="ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="REFNO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Motor" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="ClientCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IDCARD" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ClientName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Address1" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumber1" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ConTractName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Address2" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumber2" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PolicyNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="RNType" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="PolicyType" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Suminsured" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Benefitialy" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Model" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CarPlate" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CHASSIS" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CarEngine" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CMI_PolicyNo" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CMI_StickerNo" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CMI_StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CMI_EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Project" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Dealer" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="InsurerCode" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="DriverName1" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DriverOld1" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DriverName2" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DriverOld2" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CarAccessories" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CMI_PaymentBy" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_CLIENT_SEARCH" Method="SP_CLIENT_SEARCH">
    <Parameter Name="clientcode" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="SP_CLIENT_SEARCHResult">
      <Column Name="ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="REFNO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Motor" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="ClientCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IDCARD" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ClientName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Address1" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumber1" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ConTractName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Address2" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumber2" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PolicyNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="RNType" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="PolicyType" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Suminsured" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Benefitialy" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Model" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CarPlate" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CHASSIS" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CarEngine" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CMI_PolicyNo" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CMI_StickerNo" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CMI_StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CMI_EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Project" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Dealer" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="InsurerCode" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="DriverName1" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DriverOld1" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DriverName2" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DriverOld2" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CarAccessories" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CMI_PaymentBy" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="REFNOOld" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MotorOld" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="ClientCodeOld" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IDCARDOld" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ClientNameOld" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Address1Old" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumber1Old" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ConTractNameOld" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Address2Old" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumber2Old" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PolicyNoOld" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="StartDateOld" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDateOld" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="StatusOld" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="RNTypeOld" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="PolicyTypeOld" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SuminsuredOld" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="BenefitialyOld" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ModelOld" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CarPlateOld" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CHASSISOld" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CarEngineOld" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CMI_PolicyNoOld" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CMI_StickerNoOld" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CMI_StartDateOld" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CMI_EndDateOld" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ProjectOld" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DealerOld" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="InsurerCodeOld" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="DriverName1Old" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DriverOld1Old" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DriverName2Old" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DriverOld2Old" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CMI_PaymentByOld" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>