'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="MotorClaim")>  _
Partial Public Class DataClasses_MotorClaimDataExtDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InserttblClaimTransaction_Data(instance As tblClaimTransaction_Data)
    End Sub
  Partial Private Sub UpdatetblClaimTransaction_Data(instance As tblClaimTransaction_Data)
    End Sub
  Partial Private Sub DeletetblClaimTransaction_Data(instance As tblClaimTransaction_Data)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings("MotorClaimConnectionString").ConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property tblClaimTransaction_Datas() As System.Data.Linq.Table(Of tblClaimTransaction_Data)
		Get
			Return Me.GetTable(Of tblClaimTransaction_Data)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.tblClaimTransaction_Data")>  _
Partial Public Class tblClaimTransaction_Data
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _TRID As Integer
	
	Private _TRNo As String
	
	Private _ClaimStatus As String
	
	Private _TempPolicy As String
	
	Private _RefNo As String
	
	Private _Version As System.Nullable(Of Integer)
	
	Private _PolicyNo As String
	
	Private _PolicyYear As System.Nullable(Of Integer)
	
	Private _ClaimNo As String
	
	Private _TransactionDate As String
	
	Private _Unwriter As String
	
	Private _InsuredName As String
	
	Private _EffectiveDate As String
	
	Private _ExpiryDate As String
	
	Private _Beneficiary As String
	
	Private _CarBrand As String
	
	Private _CarModel As String
	
	Private _CarLicense As String
	
	Private _CarYear As String
	
	Private _ChassisNo As String
	
	Private _ShowRoomName As String
	
	Private _ShowRoomCode As String
	
	Private _ClaimNoticeDate As String
	
	Private _ClaimNoticeTime As String
	
	Private _ClaimDetails As String
	
	Private _ClaimType As System.Nullable(Of Integer)
	
	Private _ClaimResult As System.Nullable(Of Integer)
	
	Private _ClaimDamageDetails As String
	
	Private _CallCenter As String
	
	Private _AccidentDate As String
	
	Private _AccidentTime As String
	
	Private _AccidentPlace As String
	
	Private _AccidentTumbon As String
	
	Private _AccidentAmphur As String
	
	Private _AccidentProvince As String
	
	Private _AccidentZipcode As String
	
	Private _DriverName As String
	
	Private _DriverTel As String
	
	Private _NoticeName As String
	
	Private _NoticeTel As String
	
	Private _GarageType As System.Nullable(Of Integer)
	
	Private _GarageCode As String
	
	Private _GarageName As String
	
	Private _GaragePlace As String
	
	Private _GarageTumbon As String
	
	Private _GarageAmphur As String
	
	Private _GarageProvince As String
	
	Private _GarageZipcode As String
	
	Private _CarRepairDate As String
	
	Private _CarReceiveDate As String
	
	Private _ConsentFormNo As String
	
	Private _PartsDealerName As String
	
	Private _PaymentDetails As String
	
	Private _Amount1 As System.Nullable(Of Double)
	
	Private _Amount2 As System.Nullable(Of Double)
	
	Private _Amount3 As System.Nullable(Of Double)
	
	Private _Remark As String
	
	Private _FileUpload As String
	
	Private _GUID As String
	
	Private _SubmitDate As System.Nullable(Of Date)
	
	Private _Status As System.Nullable(Of Boolean)
	
	Private _IsPost As System.Nullable(Of Boolean)
	
	Private _ip As String
	
	Private _PostDate As System.Nullable(Of Date)
	
	Private _AgentCode As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnTRIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnTRIDChanged()
    End Sub
    Partial Private Sub OnTRNoChanging(value As String)
    End Sub
    Partial Private Sub OnTRNoChanged()
    End Sub
    Partial Private Sub OnClaimStatusChanging(value As String)
    End Sub
    Partial Private Sub OnClaimStatusChanged()
    End Sub
    Partial Private Sub OnTempPolicyChanging(value As String)
    End Sub
    Partial Private Sub OnTempPolicyChanged()
    End Sub
    Partial Private Sub OnRefNoChanging(value As String)
    End Sub
    Partial Private Sub OnRefNoChanged()
    End Sub
    Partial Private Sub OnVersionChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnVersionChanged()
    End Sub
    Partial Private Sub OnPolicyNoChanging(value As String)
    End Sub
    Partial Private Sub OnPolicyNoChanged()
    End Sub
    Partial Private Sub OnPolicyYearChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnPolicyYearChanged()
    End Sub
    Partial Private Sub OnClaimNoChanging(value As String)
    End Sub
    Partial Private Sub OnClaimNoChanged()
    End Sub
    Partial Private Sub OnTransactionDateChanging(value As String)
    End Sub
    Partial Private Sub OnTransactionDateChanged()
    End Sub
    Partial Private Sub OnUnwriterChanging(value As String)
    End Sub
    Partial Private Sub OnUnwriterChanged()
    End Sub
    Partial Private Sub OnInsuredNameChanging(value As String)
    End Sub
    Partial Private Sub OnInsuredNameChanged()
    End Sub
    Partial Private Sub OnEffectiveDateChanging(value As String)
    End Sub
    Partial Private Sub OnEffectiveDateChanged()
    End Sub
    Partial Private Sub OnExpiryDateChanging(value As String)
    End Sub
    Partial Private Sub OnExpiryDateChanged()
    End Sub
    Partial Private Sub OnBeneficiaryChanging(value As String)
    End Sub
    Partial Private Sub OnBeneficiaryChanged()
    End Sub
    Partial Private Sub OnCarBrandChanging(value As String)
    End Sub
    Partial Private Sub OnCarBrandChanged()
    End Sub
    Partial Private Sub OnCarModelChanging(value As String)
    End Sub
    Partial Private Sub OnCarModelChanged()
    End Sub
    Partial Private Sub OnCarLicenseChanging(value As String)
    End Sub
    Partial Private Sub OnCarLicenseChanged()
    End Sub
    Partial Private Sub OnCarYearChanging(value As String)
    End Sub
    Partial Private Sub OnCarYearChanged()
    End Sub
    Partial Private Sub OnChassisNoChanging(value As String)
    End Sub
    Partial Private Sub OnChassisNoChanged()
    End Sub
    Partial Private Sub OnShowRoomNameChanging(value As String)
    End Sub
    Partial Private Sub OnShowRoomNameChanged()
    End Sub
    Partial Private Sub OnShowRoomCodeChanging(value As String)
    End Sub
    Partial Private Sub OnShowRoomCodeChanged()
    End Sub
    Partial Private Sub OnClaimNoticeDateChanging(value As String)
    End Sub
    Partial Private Sub OnClaimNoticeDateChanged()
    End Sub
    Partial Private Sub OnClaimNoticeTimeChanging(value As String)
    End Sub
    Partial Private Sub OnClaimNoticeTimeChanged()
    End Sub
    Partial Private Sub OnClaimDetailsChanging(value As String)
    End Sub
    Partial Private Sub OnClaimDetailsChanged()
    End Sub
    Partial Private Sub OnClaimTypeChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnClaimTypeChanged()
    End Sub
    Partial Private Sub OnClaimResultChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnClaimResultChanged()
    End Sub
    Partial Private Sub OnClaimDamageDetailsChanging(value As String)
    End Sub
    Partial Private Sub OnClaimDamageDetailsChanged()
    End Sub
    Partial Private Sub OnCallCenterChanging(value As String)
    End Sub
    Partial Private Sub OnCallCenterChanged()
    End Sub
    Partial Private Sub OnAccidentDateChanging(value As String)
    End Sub
    Partial Private Sub OnAccidentDateChanged()
    End Sub
    Partial Private Sub OnAccidentTimeChanging(value As String)
    End Sub
    Partial Private Sub OnAccidentTimeChanged()
    End Sub
    Partial Private Sub OnAccidentPlaceChanging(value As String)
    End Sub
    Partial Private Sub OnAccidentPlaceChanged()
    End Sub
    Partial Private Sub OnAccidentTumbonChanging(value As String)
    End Sub
    Partial Private Sub OnAccidentTumbonChanged()
    End Sub
    Partial Private Sub OnAccidentAmphurChanging(value As String)
    End Sub
    Partial Private Sub OnAccidentAmphurChanged()
    End Sub
    Partial Private Sub OnAccidentProvinceChanging(value As String)
    End Sub
    Partial Private Sub OnAccidentProvinceChanged()
    End Sub
    Partial Private Sub OnAccidentZipcodeChanging(value As String)
    End Sub
    Partial Private Sub OnAccidentZipcodeChanged()
    End Sub
    Partial Private Sub OnDriverNameChanging(value As String)
    End Sub
    Partial Private Sub OnDriverNameChanged()
    End Sub
    Partial Private Sub OnDriverTelChanging(value As String)
    End Sub
    Partial Private Sub OnDriverTelChanged()
    End Sub
    Partial Private Sub OnNoticeNameChanging(value As String)
    End Sub
    Partial Private Sub OnNoticeNameChanged()
    End Sub
    Partial Private Sub OnNoticeTelChanging(value As String)
    End Sub
    Partial Private Sub OnNoticeTelChanged()
    End Sub
    Partial Private Sub OnGarageTypeChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnGarageTypeChanged()
    End Sub
    Partial Private Sub OnGarageCodeChanging(value As String)
    End Sub
    Partial Private Sub OnGarageCodeChanged()
    End Sub
    Partial Private Sub OnGarageNameChanging(value As String)
    End Sub
    Partial Private Sub OnGarageNameChanged()
    End Sub
    Partial Private Sub OnGaragePlaceChanging(value As String)
    End Sub
    Partial Private Sub OnGaragePlaceChanged()
    End Sub
    Partial Private Sub OnGarageTumbonChanging(value As String)
    End Sub
    Partial Private Sub OnGarageTumbonChanged()
    End Sub
    Partial Private Sub OnGarageAmphurChanging(value As String)
    End Sub
    Partial Private Sub OnGarageAmphurChanged()
    End Sub
    Partial Private Sub OnGarageProvinceChanging(value As String)
    End Sub
    Partial Private Sub OnGarageProvinceChanged()
    End Sub
    Partial Private Sub OnGarageZipcodeChanging(value As String)
    End Sub
    Partial Private Sub OnGarageZipcodeChanged()
    End Sub
    Partial Private Sub OnCarRepairDateChanging(value As String)
    End Sub
    Partial Private Sub OnCarRepairDateChanged()
    End Sub
    Partial Private Sub OnCarReceiveDateChanging(value As String)
    End Sub
    Partial Private Sub OnCarReceiveDateChanged()
    End Sub
    Partial Private Sub OnConsentFormNoChanging(value As String)
    End Sub
    Partial Private Sub OnConsentFormNoChanged()
    End Sub
    Partial Private Sub OnPartsDealerNameChanging(value As String)
    End Sub
    Partial Private Sub OnPartsDealerNameChanged()
    End Sub
    Partial Private Sub OnPaymentDetailsChanging(value As String)
    End Sub
    Partial Private Sub OnPaymentDetailsChanged()
    End Sub
    Partial Private Sub OnAmount1Changing(value As System.Nullable(Of Double))
    End Sub
    Partial Private Sub OnAmount1Changed()
    End Sub
    Partial Private Sub OnAmount2Changing(value As System.Nullable(Of Double))
    End Sub
    Partial Private Sub OnAmount2Changed()
    End Sub
    Partial Private Sub OnAmount3Changing(value As System.Nullable(Of Double))
    End Sub
    Partial Private Sub OnAmount3Changed()
    End Sub
    Partial Private Sub OnRemarkChanging(value As String)
    End Sub
    Partial Private Sub OnRemarkChanged()
    End Sub
    Partial Private Sub OnFileUploadChanging(value As String)
    End Sub
    Partial Private Sub OnFileUploadChanged()
    End Sub
    Partial Private Sub OnGUIDChanging(value As String)
    End Sub
    Partial Private Sub OnGUIDChanged()
    End Sub
    Partial Private Sub OnSubmitDateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnSubmitDateChanged()
    End Sub
    Partial Private Sub OnStatusChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnStatusChanged()
    End Sub
    Partial Private Sub OnIsPostChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnIsPostChanged()
    End Sub
    Partial Private Sub OnipChanging(value As String)
    End Sub
    Partial Private Sub OnipChanged()
    End Sub
    Partial Private Sub OnPostDateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnPostDateChanged()
    End Sub
    Partial Private Sub OnAgentCodeChanging(value As String)
    End Sub
    Partial Private Sub OnAgentCodeChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TRID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property TRID() As Integer
		Get
			Return Me._TRID
		End Get
		Set
			If ((Me._TRID = value)  _
						= false) Then
				Me.OnTRIDChanging(value)
				Me.SendPropertyChanging
				Me._TRID = value
				Me.SendPropertyChanged("TRID")
				Me.OnTRIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TRNo", DbType:="VarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property TRNo() As String
		Get
			Return Me._TRNo
		End Get
		Set
			If (String.Equals(Me._TRNo, value) = false) Then
				Me.OnTRNoChanging(value)
				Me.SendPropertyChanging
				Me._TRNo = value
				Me.SendPropertyChanged("TRNo")
				Me.OnTRNoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ClaimStatus", DbType:="VarChar(50)")>  _
	Public Property ClaimStatus() As String
		Get
			Return Me._ClaimStatus
		End Get
		Set
			If (String.Equals(Me._ClaimStatus, value) = false) Then
				Me.OnClaimStatusChanging(value)
				Me.SendPropertyChanging
				Me._ClaimStatus = value
				Me.SendPropertyChanged("ClaimStatus")
				Me.OnClaimStatusChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TempPolicy", DbType:="VarChar(100)")>  _
	Public Property TempPolicy() As String
		Get
			Return Me._TempPolicy
		End Get
		Set
			If (String.Equals(Me._TempPolicy, value) = false) Then
				Me.OnTempPolicyChanging(value)
				Me.SendPropertyChanging
				Me._TempPolicy = value
				Me.SendPropertyChanged("TempPolicy")
				Me.OnTempPolicyChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RefNo", DbType:="VarChar(100)")>  _
	Public Property RefNo() As String
		Get
			Return Me._RefNo
		End Get
		Set
			If (String.Equals(Me._RefNo, value) = false) Then
				Me.OnRefNoChanging(value)
				Me.SendPropertyChanging
				Me._RefNo = value
				Me.SendPropertyChanged("RefNo")
				Me.OnRefNoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Version", DbType:="Int")>  _
	Public Property Version() As System.Nullable(Of Integer)
		Get
			Return Me._Version
		End Get
		Set
			If (Me._Version.Equals(value) = false) Then
				Me.OnVersionChanging(value)
				Me.SendPropertyChanging
				Me._Version = value
				Me.SendPropertyChanged("Version")
				Me.OnVersionChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PolicyNo", DbType:="VarChar(100)")>  _
	Public Property PolicyNo() As String
		Get
			Return Me._PolicyNo
		End Get
		Set
			If (String.Equals(Me._PolicyNo, value) = false) Then
				Me.OnPolicyNoChanging(value)
				Me.SendPropertyChanging
				Me._PolicyNo = value
				Me.SendPropertyChanged("PolicyNo")
				Me.OnPolicyNoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PolicyYear", DbType:="Int")>  _
	Public Property PolicyYear() As System.Nullable(Of Integer)
		Get
			Return Me._PolicyYear
		End Get
		Set
			If (Me._PolicyYear.Equals(value) = false) Then
				Me.OnPolicyYearChanging(value)
				Me.SendPropertyChanging
				Me._PolicyYear = value
				Me.SendPropertyChanged("PolicyYear")
				Me.OnPolicyYearChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ClaimNo", DbType:="VarChar(100)")>  _
	Public Property ClaimNo() As String
		Get
			Return Me._ClaimNo
		End Get
		Set
			If (String.Equals(Me._ClaimNo, value) = false) Then
				Me.OnClaimNoChanging(value)
				Me.SendPropertyChanging
				Me._ClaimNo = value
				Me.SendPropertyChanged("ClaimNo")
				Me.OnClaimNoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TransactionDate", DbType:="VarChar(10)")>  _
	Public Property TransactionDate() As String
		Get
			Return Me._TransactionDate
		End Get
		Set
			If (String.Equals(Me._TransactionDate, value) = false) Then
				Me.OnTransactionDateChanging(value)
				Me.SendPropertyChanging
				Me._TransactionDate = value
				Me.SendPropertyChanged("TransactionDate")
				Me.OnTransactionDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Unwriter", DbType:="VarChar(10)")>  _
	Public Property Unwriter() As String
		Get
			Return Me._Unwriter
		End Get
		Set
			If (String.Equals(Me._Unwriter, value) = false) Then
				Me.OnUnwriterChanging(value)
				Me.SendPropertyChanging
				Me._Unwriter = value
				Me.SendPropertyChanged("Unwriter")
				Me.OnUnwriterChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_InsuredName", DbType:="VarChar(255)")>  _
	Public Property InsuredName() As String
		Get
			Return Me._InsuredName
		End Get
		Set
			If (String.Equals(Me._InsuredName, value) = false) Then
				Me.OnInsuredNameChanging(value)
				Me.SendPropertyChanging
				Me._InsuredName = value
				Me.SendPropertyChanged("InsuredName")
				Me.OnInsuredNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EffectiveDate", DbType:="VarChar(10)")>  _
	Public Property EffectiveDate() As String
		Get
			Return Me._EffectiveDate
		End Get
		Set
			If (String.Equals(Me._EffectiveDate, value) = false) Then
				Me.OnEffectiveDateChanging(value)
				Me.SendPropertyChanging
				Me._EffectiveDate = value
				Me.SendPropertyChanged("EffectiveDate")
				Me.OnEffectiveDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ExpiryDate", DbType:="VarChar(10)")>  _
	Public Property ExpiryDate() As String
		Get
			Return Me._ExpiryDate
		End Get
		Set
			If (String.Equals(Me._ExpiryDate, value) = false) Then
				Me.OnExpiryDateChanging(value)
				Me.SendPropertyChanging
				Me._ExpiryDate = value
				Me.SendPropertyChanged("ExpiryDate")
				Me.OnExpiryDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Beneficiary", DbType:="VarChar(255)")>  _
	Public Property Beneficiary() As String
		Get
			Return Me._Beneficiary
		End Get
		Set
			If (String.Equals(Me._Beneficiary, value) = false) Then
				Me.OnBeneficiaryChanging(value)
				Me.SendPropertyChanging
				Me._Beneficiary = value
				Me.SendPropertyChanged("Beneficiary")
				Me.OnBeneficiaryChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CarBrand", DbType:="VarChar(50)")>  _
	Public Property CarBrand() As String
		Get
			Return Me._CarBrand
		End Get
		Set
			If (String.Equals(Me._CarBrand, value) = false) Then
				Me.OnCarBrandChanging(value)
				Me.SendPropertyChanging
				Me._CarBrand = value
				Me.SendPropertyChanged("CarBrand")
				Me.OnCarBrandChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CarModel", DbType:="VarChar(100)")>  _
	Public Property CarModel() As String
		Get
			Return Me._CarModel
		End Get
		Set
			If (String.Equals(Me._CarModel, value) = false) Then
				Me.OnCarModelChanging(value)
				Me.SendPropertyChanging
				Me._CarModel = value
				Me.SendPropertyChanged("CarModel")
				Me.OnCarModelChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CarLicense", DbType:="VarChar(50)")>  _
	Public Property CarLicense() As String
		Get
			Return Me._CarLicense
		End Get
		Set
			If (String.Equals(Me._CarLicense, value) = false) Then
				Me.OnCarLicenseChanging(value)
				Me.SendPropertyChanging
				Me._CarLicense = value
				Me.SendPropertyChanged("CarLicense")
				Me.OnCarLicenseChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CarYear", DbType:="VarChar(50)")>  _
	Public Property CarYear() As String
		Get
			Return Me._CarYear
		End Get
		Set
			If (String.Equals(Me._CarYear, value) = false) Then
				Me.OnCarYearChanging(value)
				Me.SendPropertyChanging
				Me._CarYear = value
				Me.SendPropertyChanged("CarYear")
				Me.OnCarYearChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ChassisNo", DbType:="VarChar(50)")>  _
	Public Property ChassisNo() As String
		Get
			Return Me._ChassisNo
		End Get
		Set
			If (String.Equals(Me._ChassisNo, value) = false) Then
				Me.OnChassisNoChanging(value)
				Me.SendPropertyChanging
				Me._ChassisNo = value
				Me.SendPropertyChanged("ChassisNo")
				Me.OnChassisNoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ShowRoomName", DbType:="VarChar(100)")>  _
	Public Property ShowRoomName() As String
		Get
			Return Me._ShowRoomName
		End Get
		Set
			If (String.Equals(Me._ShowRoomName, value) = false) Then
				Me.OnShowRoomNameChanging(value)
				Me.SendPropertyChanging
				Me._ShowRoomName = value
				Me.SendPropertyChanged("ShowRoomName")
				Me.OnShowRoomNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ShowRoomCode", DbType:="VarChar(10)")>  _
	Public Property ShowRoomCode() As String
		Get
			Return Me._ShowRoomCode
		End Get
		Set
			If (String.Equals(Me._ShowRoomCode, value) = false) Then
				Me.OnShowRoomCodeChanging(value)
				Me.SendPropertyChanging
				Me._ShowRoomCode = value
				Me.SendPropertyChanged("ShowRoomCode")
				Me.OnShowRoomCodeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ClaimNoticeDate", DbType:="VarChar(10)")>  _
	Public Property ClaimNoticeDate() As String
		Get
			Return Me._ClaimNoticeDate
		End Get
		Set
			If (String.Equals(Me._ClaimNoticeDate, value) = false) Then
				Me.OnClaimNoticeDateChanging(value)
				Me.SendPropertyChanging
				Me._ClaimNoticeDate = value
				Me.SendPropertyChanged("ClaimNoticeDate")
				Me.OnClaimNoticeDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ClaimNoticeTime", DbType:="VarChar(10)")>  _
	Public Property ClaimNoticeTime() As String
		Get
			Return Me._ClaimNoticeTime
		End Get
		Set
			If (String.Equals(Me._ClaimNoticeTime, value) = false) Then
				Me.OnClaimNoticeTimeChanging(value)
				Me.SendPropertyChanging
				Me._ClaimNoticeTime = value
				Me.SendPropertyChanged("ClaimNoticeTime")
				Me.OnClaimNoticeTimeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ClaimDetails", DbType:="VarChar(255)")>  _
	Public Property ClaimDetails() As String
		Get
			Return Me._ClaimDetails
		End Get
		Set
			If (String.Equals(Me._ClaimDetails, value) = false) Then
				Me.OnClaimDetailsChanging(value)
				Me.SendPropertyChanging
				Me._ClaimDetails = value
				Me.SendPropertyChanged("ClaimDetails")
				Me.OnClaimDetailsChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ClaimType", DbType:="Int")>  _
	Public Property ClaimType() As System.Nullable(Of Integer)
		Get
			Return Me._ClaimType
		End Get
		Set
			If (Me._ClaimType.Equals(value) = false) Then
				Me.OnClaimTypeChanging(value)
				Me.SendPropertyChanging
				Me._ClaimType = value
				Me.SendPropertyChanged("ClaimType")
				Me.OnClaimTypeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ClaimResult", DbType:="Int")>  _
	Public Property ClaimResult() As System.Nullable(Of Integer)
		Get
			Return Me._ClaimResult
		End Get
		Set
			If (Me._ClaimResult.Equals(value) = false) Then
				Me.OnClaimResultChanging(value)
				Me.SendPropertyChanging
				Me._ClaimResult = value
				Me.SendPropertyChanged("ClaimResult")
				Me.OnClaimResultChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ClaimDamageDetails", DbType:="VarChar(MAX)")>  _
	Public Property ClaimDamageDetails() As String
		Get
			Return Me._ClaimDamageDetails
		End Get
		Set
			If (String.Equals(Me._ClaimDamageDetails, value) = false) Then
				Me.OnClaimDamageDetailsChanging(value)
				Me.SendPropertyChanging
				Me._ClaimDamageDetails = value
				Me.SendPropertyChanged("ClaimDamageDetails")
				Me.OnClaimDamageDetailsChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CallCenter", DbType:="VarChar(50)")>  _
	Public Property CallCenter() As String
		Get
			Return Me._CallCenter
		End Get
		Set
			If (String.Equals(Me._CallCenter, value) = false) Then
				Me.OnCallCenterChanging(value)
				Me.SendPropertyChanging
				Me._CallCenter = value
				Me.SendPropertyChanged("CallCenter")
				Me.OnCallCenterChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AccidentDate", DbType:="VarChar(10)")>  _
	Public Property AccidentDate() As String
		Get
			Return Me._AccidentDate
		End Get
		Set
			If (String.Equals(Me._AccidentDate, value) = false) Then
				Me.OnAccidentDateChanging(value)
				Me.SendPropertyChanging
				Me._AccidentDate = value
				Me.SendPropertyChanged("AccidentDate")
				Me.OnAccidentDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AccidentTime", DbType:="VarChar(10)")>  _
	Public Property AccidentTime() As String
		Get
			Return Me._AccidentTime
		End Get
		Set
			If (String.Equals(Me._AccidentTime, value) = false) Then
				Me.OnAccidentTimeChanging(value)
				Me.SendPropertyChanging
				Me._AccidentTime = value
				Me.SendPropertyChanged("AccidentTime")
				Me.OnAccidentTimeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AccidentPlace", DbType:="VarChar(255)")>  _
	Public Property AccidentPlace() As String
		Get
			Return Me._AccidentPlace
		End Get
		Set
			If (String.Equals(Me._AccidentPlace, value) = false) Then
				Me.OnAccidentPlaceChanging(value)
				Me.SendPropertyChanging
				Me._AccidentPlace = value
				Me.SendPropertyChanged("AccidentPlace")
				Me.OnAccidentPlaceChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AccidentTumbon", DbType:="VarChar(255)")>  _
	Public Property AccidentTumbon() As String
		Get
			Return Me._AccidentTumbon
		End Get
		Set
			If (String.Equals(Me._AccidentTumbon, value) = false) Then
				Me.OnAccidentTumbonChanging(value)
				Me.SendPropertyChanging
				Me._AccidentTumbon = value
				Me.SendPropertyChanged("AccidentTumbon")
				Me.OnAccidentTumbonChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AccidentAmphur", DbType:="VarChar(255)")>  _
	Public Property AccidentAmphur() As String
		Get
			Return Me._AccidentAmphur
		End Get
		Set
			If (String.Equals(Me._AccidentAmphur, value) = false) Then
				Me.OnAccidentAmphurChanging(value)
				Me.SendPropertyChanging
				Me._AccidentAmphur = value
				Me.SendPropertyChanged("AccidentAmphur")
				Me.OnAccidentAmphurChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AccidentProvince", DbType:="VarChar(255)")>  _
	Public Property AccidentProvince() As String
		Get
			Return Me._AccidentProvince
		End Get
		Set
			If (String.Equals(Me._AccidentProvince, value) = false) Then
				Me.OnAccidentProvinceChanging(value)
				Me.SendPropertyChanging
				Me._AccidentProvince = value
				Me.SendPropertyChanged("AccidentProvince")
				Me.OnAccidentProvinceChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AccidentZipcode", DbType:="VarChar(5)")>  _
	Public Property AccidentZipcode() As String
		Get
			Return Me._AccidentZipcode
		End Get
		Set
			If (String.Equals(Me._AccidentZipcode, value) = false) Then
				Me.OnAccidentZipcodeChanging(value)
				Me.SendPropertyChanging
				Me._AccidentZipcode = value
				Me.SendPropertyChanged("AccidentZipcode")
				Me.OnAccidentZipcodeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DriverName", DbType:="VarChar(255)")>  _
	Public Property DriverName() As String
		Get
			Return Me._DriverName
		End Get
		Set
			If (String.Equals(Me._DriverName, value) = false) Then
				Me.OnDriverNameChanging(value)
				Me.SendPropertyChanging
				Me._DriverName = value
				Me.SendPropertyChanged("DriverName")
				Me.OnDriverNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DriverTel", DbType:="VarChar(100)")>  _
	Public Property DriverTel() As String
		Get
			Return Me._DriverTel
		End Get
		Set
			If (String.Equals(Me._DriverTel, value) = false) Then
				Me.OnDriverTelChanging(value)
				Me.SendPropertyChanging
				Me._DriverTel = value
				Me.SendPropertyChanged("DriverTel")
				Me.OnDriverTelChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NoticeName", DbType:="VarChar(255)")>  _
	Public Property NoticeName() As String
		Get
			Return Me._NoticeName
		End Get
		Set
			If (String.Equals(Me._NoticeName, value) = false) Then
				Me.OnNoticeNameChanging(value)
				Me.SendPropertyChanging
				Me._NoticeName = value
				Me.SendPropertyChanged("NoticeName")
				Me.OnNoticeNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NoticeTel", DbType:="VarChar(100)")>  _
	Public Property NoticeTel() As String
		Get
			Return Me._NoticeTel
		End Get
		Set
			If (String.Equals(Me._NoticeTel, value) = false) Then
				Me.OnNoticeTelChanging(value)
				Me.SendPropertyChanging
				Me._NoticeTel = value
				Me.SendPropertyChanged("NoticeTel")
				Me.OnNoticeTelChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_GarageType", DbType:="Int")>  _
	Public Property GarageType() As System.Nullable(Of Integer)
		Get
			Return Me._GarageType
		End Get
		Set
			If (Me._GarageType.Equals(value) = false) Then
				Me.OnGarageTypeChanging(value)
				Me.SendPropertyChanging
				Me._GarageType = value
				Me.SendPropertyChanged("GarageType")
				Me.OnGarageTypeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_GarageCode", DbType:="VarChar(10)")>  _
	Public Property GarageCode() As String
		Get
			Return Me._GarageCode
		End Get
		Set
			If (String.Equals(Me._GarageCode, value) = false) Then
				Me.OnGarageCodeChanging(value)
				Me.SendPropertyChanging
				Me._GarageCode = value
				Me.SendPropertyChanged("GarageCode")
				Me.OnGarageCodeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_GarageName", DbType:="VarChar(100)")>  _
	Public Property GarageName() As String
		Get
			Return Me._GarageName
		End Get
		Set
			If (String.Equals(Me._GarageName, value) = false) Then
				Me.OnGarageNameChanging(value)
				Me.SendPropertyChanging
				Me._GarageName = value
				Me.SendPropertyChanged("GarageName")
				Me.OnGarageNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_GaragePlace", DbType:="VarChar(255)")>  _
	Public Property GaragePlace() As String
		Get
			Return Me._GaragePlace
		End Get
		Set
			If (String.Equals(Me._GaragePlace, value) = false) Then
				Me.OnGaragePlaceChanging(value)
				Me.SendPropertyChanging
				Me._GaragePlace = value
				Me.SendPropertyChanged("GaragePlace")
				Me.OnGaragePlaceChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_GarageTumbon", DbType:="VarChar(255)")>  _
	Public Property GarageTumbon() As String
		Get
			Return Me._GarageTumbon
		End Get
		Set
			If (String.Equals(Me._GarageTumbon, value) = false) Then
				Me.OnGarageTumbonChanging(value)
				Me.SendPropertyChanging
				Me._GarageTumbon = value
				Me.SendPropertyChanged("GarageTumbon")
				Me.OnGarageTumbonChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_GarageAmphur", DbType:="VarChar(255)")>  _
	Public Property GarageAmphur() As String
		Get
			Return Me._GarageAmphur
		End Get
		Set
			If (String.Equals(Me._GarageAmphur, value) = false) Then
				Me.OnGarageAmphurChanging(value)
				Me.SendPropertyChanging
				Me._GarageAmphur = value
				Me.SendPropertyChanged("GarageAmphur")
				Me.OnGarageAmphurChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_GarageProvince", DbType:="VarChar(255)")>  _
	Public Property GarageProvince() As String
		Get
			Return Me._GarageProvince
		End Get
		Set
			If (String.Equals(Me._GarageProvince, value) = false) Then
				Me.OnGarageProvinceChanging(value)
				Me.SendPropertyChanging
				Me._GarageProvince = value
				Me.SendPropertyChanged("GarageProvince")
				Me.OnGarageProvinceChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_GarageZipcode", DbType:="VarChar(5)")>  _
	Public Property GarageZipcode() As String
		Get
			Return Me._GarageZipcode
		End Get
		Set
			If (String.Equals(Me._GarageZipcode, value) = false) Then
				Me.OnGarageZipcodeChanging(value)
				Me.SendPropertyChanging
				Me._GarageZipcode = value
				Me.SendPropertyChanged("GarageZipcode")
				Me.OnGarageZipcodeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CarRepairDate", DbType:="VarChar(10)")>  _
	Public Property CarRepairDate() As String
		Get
			Return Me._CarRepairDate
		End Get
		Set
			If (String.Equals(Me._CarRepairDate, value) = false) Then
				Me.OnCarRepairDateChanging(value)
				Me.SendPropertyChanging
				Me._CarRepairDate = value
				Me.SendPropertyChanged("CarRepairDate")
				Me.OnCarRepairDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CarReceiveDate", DbType:="VarChar(10)")>  _
	Public Property CarReceiveDate() As String
		Get
			Return Me._CarReceiveDate
		End Get
		Set
			If (String.Equals(Me._CarReceiveDate, value) = false) Then
				Me.OnCarReceiveDateChanging(value)
				Me.SendPropertyChanging
				Me._CarReceiveDate = value
				Me.SendPropertyChanged("CarReceiveDate")
				Me.OnCarReceiveDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ConsentFormNo", DbType:="VarChar(50)")>  _
	Public Property ConsentFormNo() As String
		Get
			Return Me._ConsentFormNo
		End Get
		Set
			If (String.Equals(Me._ConsentFormNo, value) = false) Then
				Me.OnConsentFormNoChanging(value)
				Me.SendPropertyChanging
				Me._ConsentFormNo = value
				Me.SendPropertyChanged("ConsentFormNo")
				Me.OnConsentFormNoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PartsDealerName", DbType:="VarChar(255)")>  _
	Public Property PartsDealerName() As String
		Get
			Return Me._PartsDealerName
		End Get
		Set
			If (String.Equals(Me._PartsDealerName, value) = false) Then
				Me.OnPartsDealerNameChanging(value)
				Me.SendPropertyChanging
				Me._PartsDealerName = value
				Me.SendPropertyChanged("PartsDealerName")
				Me.OnPartsDealerNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PaymentDetails", DbType:="VarChar(MAX)")>  _
	Public Property PaymentDetails() As String
		Get
			Return Me._PaymentDetails
		End Get
		Set
			If (String.Equals(Me._PaymentDetails, value) = false) Then
				Me.OnPaymentDetailsChanging(value)
				Me.SendPropertyChanging
				Me._PaymentDetails = value
				Me.SendPropertyChanged("PaymentDetails")
				Me.OnPaymentDetailsChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Amount1", DbType:="Float")>  _
	Public Property Amount1() As System.Nullable(Of Double)
		Get
			Return Me._Amount1
		End Get
		Set
			If (Me._Amount1.Equals(value) = false) Then
				Me.OnAmount1Changing(value)
				Me.SendPropertyChanging
				Me._Amount1 = value
				Me.SendPropertyChanged("Amount1")
				Me.OnAmount1Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Amount2", DbType:="Float")>  _
	Public Property Amount2() As System.Nullable(Of Double)
		Get
			Return Me._Amount2
		End Get
		Set
			If (Me._Amount2.Equals(value) = false) Then
				Me.OnAmount2Changing(value)
				Me.SendPropertyChanging
				Me._Amount2 = value
				Me.SendPropertyChanged("Amount2")
				Me.OnAmount2Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Amount3", DbType:="Float")>  _
	Public Property Amount3() As System.Nullable(Of Double)
		Get
			Return Me._Amount3
		End Get
		Set
			If (Me._Amount3.Equals(value) = false) Then
				Me.OnAmount3Changing(value)
				Me.SendPropertyChanging
				Me._Amount3 = value
				Me.SendPropertyChanged("Amount3")
				Me.OnAmount3Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Remark", DbType:="VarChar(255)")>  _
	Public Property Remark() As String
		Get
			Return Me._Remark
		End Get
		Set
			If (String.Equals(Me._Remark, value) = false) Then
				Me.OnRemarkChanging(value)
				Me.SendPropertyChanging
				Me._Remark = value
				Me.SendPropertyChanged("Remark")
				Me.OnRemarkChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FileUpload", DbType:="VarChar(255)")>  _
	Public Property FileUpload() As String
		Get
			Return Me._FileUpload
		End Get
		Set
			If (String.Equals(Me._FileUpload, value) = false) Then
				Me.OnFileUploadChanging(value)
				Me.SendPropertyChanging
				Me._FileUpload = value
				Me.SendPropertyChanged("FileUpload")
				Me.OnFileUploadChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_GUID", DbType:="VarChar(255)")>  _
	Public Property GUID() As String
		Get
			Return Me._GUID
		End Get
		Set
			If (String.Equals(Me._GUID, value) = false) Then
				Me.OnGUIDChanging(value)
				Me.SendPropertyChanging
				Me._GUID = value
				Me.SendPropertyChanged("GUID")
				Me.OnGUIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SubmitDate", DbType:="DateTime")>  _
	Public Property SubmitDate() As System.Nullable(Of Date)
		Get
			Return Me._SubmitDate
		End Get
		Set
			If (Me._SubmitDate.Equals(value) = false) Then
				Me.OnSubmitDateChanging(value)
				Me.SendPropertyChanging
				Me._SubmitDate = value
				Me.SendPropertyChanged("SubmitDate")
				Me.OnSubmitDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Status", DbType:="Bit")>  _
	Public Property Status() As System.Nullable(Of Boolean)
		Get
			Return Me._Status
		End Get
		Set
			If (Me._Status.Equals(value) = false) Then
				Me.OnStatusChanging(value)
				Me.SendPropertyChanging
				Me._Status = value
				Me.SendPropertyChanged("Status")
				Me.OnStatusChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IsPost", DbType:="Bit")>  _
	Public Property IsPost() As System.Nullable(Of Boolean)
		Get
			Return Me._IsPost
		End Get
		Set
			If (Me._IsPost.Equals(value) = false) Then
				Me.OnIsPostChanging(value)
				Me.SendPropertyChanging
				Me._IsPost = value
				Me.SendPropertyChanged("IsPost")
				Me.OnIsPostChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ip", DbType:="VarChar(50)")>  _
	Public Property ip() As String
		Get
			Return Me._ip
		End Get
		Set
			If (String.Equals(Me._ip, value) = false) Then
				Me.OnipChanging(value)
				Me.SendPropertyChanging
				Me._ip = value
				Me.SendPropertyChanged("ip")
				Me.OnipChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PostDate", DbType:="DateTime")>  _
	Public Property PostDate() As System.Nullable(Of Date)
		Get
			Return Me._PostDate
		End Get
		Set
			If (Me._PostDate.Equals(value) = false) Then
				Me.OnPostDateChanging(value)
				Me.SendPropertyChanging
				Me._PostDate = value
				Me.SendPropertyChanged("PostDate")
				Me.OnPostDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AgentCode", DbType:="VarChar(50)")>  _
	Public Property AgentCode() As String
		Get
			Return Me._AgentCode
		End Get
		Set
			If (String.Equals(Me._AgentCode, value) = false) Then
				Me.OnAgentCodeChanging(value)
				Me.SendPropertyChanging
				Me._AgentCode = value
				Me.SendPropertyChanged("AgentCode")
				Me.OnAgentCodeChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
