<?xml version="1.0" encoding="utf-8"?><Database Name="MotorClaim" Class="DataClasses_MotorClaimDataExtDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=lockthbnk-db07;Initial Catalog=MotorClaim;User ID=locksql" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="MotorClaimConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblClaimTransaction_Data" Member="tblClaimTransaction_Datas">
    <Type Name="tblClaimTransaction_Data">
      <Column Name="TRID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TRNo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ClaimStatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TempPolicy" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="RefNo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Version" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PolicyNo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PolicyYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClaimNo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TransactionDate" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Unwriter" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="InsuredName" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="EffectiveDate" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ExpiryDate" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Beneficiary" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CarBrand" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CarModel" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CarLicense" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CarYear" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ChassisNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ShowRoomName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ShowRoomCode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ClaimNoticeDate" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ClaimNoticeTime" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ClaimDetails" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ClaimType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClaimResult" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClaimDamageDetails" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CallCenter" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AccidentDate" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="AccidentTime" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="AccidentPlace" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="AccidentTumbon" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="AccidentAmphur" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="AccidentProvince" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="AccidentZipcode" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="DriverName" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DriverTel" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NoticeName" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="NoticeTel" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="GarageType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GarageCode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="GarageName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="GaragePlace" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="GarageTumbon" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="GarageAmphur" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="GarageProvince" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="GarageZipcode" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="CarRepairDate" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CarReceiveDate" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ConsentFormNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PartsDealerName" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="PaymentDetails" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Amount1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Amount2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Amount3" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="FileUpload" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="GUID" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="SubmitDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsPost" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ip" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PostDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AgentCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>