'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="LWTReports")>  _
Partial Public Class DataClasses_LWTReports_NLTDBDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertTblClaimDaily(instance As TblClaimDaily)
    End Sub
  Partial Private Sub UpdateTblClaimDaily(instance As TblClaimDaily)
    End Sub
  Partial Private Sub DeleteTblClaimDaily(instance As TblClaimDaily)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings("LWTReportsConnectionString").ConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property V_TbClaimDataV2s() As System.Data.Linq.Table(Of V_TbClaimDataV2)
		Get
			Return Me.GetTable(Of V_TbClaimDataV2)
		End Get
	End Property
	
	Public ReadOnly Property TblClaimDailies() As System.Data.Linq.Table(Of TblClaimDaily)
		Get
			Return Me.GetTable(Of TblClaimDaily)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.V_TbClaimDataV2")>  _
Partial Public Class V_TbClaimDataV2
	
	Private _ID As Integer
	
	Private _FullCustomerName As String
	
	Private _ChassisNo As String
	
	Private _PolicyNo As String
	
	Private _Insurance_ClaimNo As String
	
	Private _GarageProvinceTH As String
	
	Private _GarageProvinceEN As String
	
	Private _AccidentDate As System.Nullable(Of Date)
	
	Private _Accident_Month As System.Nullable(Of Date)
	
	Private _ClaimGroup As System.Nullable(Of Double)
	
	Private _IndemnityGroup As System.Nullable(Of Double)
	
	Private _No_of_Claim As System.Nullable(Of Double)
	
	Private _ClaimCost As System.Nullable(Of Double)
	
	Private _IndemnityType As String
	
	Private _IndemnityType_E As String
	
	Private _GarageName As String
	
	Private _GarageType1 As String
	
	Private _GarageType2 As String
	
	Private _InsurerName As String
	
	Private _InsurerCode As String
	
	Private _CustType As String
	
	Private _App_StartingDate As System.Nullable(Of Date)
	
	Private _Starting_Month As System.Nullable(Of Date)
	
	Private _Starting_Year As String
	
	Private _App_EndDate As System.Nullable(Of Date)
	
	Private _App_ShowroomName As String
	
	Private _App_Beneficiary As String
	
	Private _App_Beneficiary_Group As String
	
	Private _App_CarGroup As String
	
	Private _App_CarGroup_F As String
	
	Private _App_CarRegistryYear As System.Nullable(Of Double)
	
	Private _Claim_Paid_Month As System.Nullable(Of Double)
	
	Private _Claim_Paid_Year As System.Nullable(Of Double)
	
	Private _ClaimPaid As System.Nullable(Of Date)
	
	Private _Accdent_Province As String
	
	Private _CarAge As System.Nullable(Of Integer)
	
	Private _GarageRegionTH As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ID", DbType:="Int NOT NULL")>  _
	Public Property ID() As Integer
		Get
			Return Me._ID
		End Get
		Set
			If ((Me._ID = value)  _
						= false) Then
				Me._ID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FullCustomerName", DbType:="NVarChar(255)")>  _
	Public Property FullCustomerName() As String
		Get
			Return Me._FullCustomerName
		End Get
		Set
			If (String.Equals(Me._FullCustomerName, value) = false) Then
				Me._FullCustomerName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ChassisNo", DbType:="NVarChar(255)")>  _
	Public Property ChassisNo() As String
		Get
			Return Me._ChassisNo
		End Get
		Set
			If (String.Equals(Me._ChassisNo, value) = false) Then
				Me._ChassisNo = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PolicyNo", DbType:="NVarChar(255)")>  _
	Public Property PolicyNo() As String
		Get
			Return Me._PolicyNo
		End Get
		Set
			If (String.Equals(Me._PolicyNo, value) = false) Then
				Me._PolicyNo = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Insurance_ClaimNo", DbType:="NVarChar(255)")>  _
	Public Property Insurance_ClaimNo() As String
		Get
			Return Me._Insurance_ClaimNo
		End Get
		Set
			If (String.Equals(Me._Insurance_ClaimNo, value) = false) Then
				Me._Insurance_ClaimNo = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_GarageProvinceTH", DbType:="NVarChar(255)")>  _
	Public Property GarageProvinceTH() As String
		Get
			Return Me._GarageProvinceTH
		End Get
		Set
			If (String.Equals(Me._GarageProvinceTH, value) = false) Then
				Me._GarageProvinceTH = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_GarageProvinceEN", DbType:="NVarChar(255)")>  _
	Public Property GarageProvinceEN() As String
		Get
			Return Me._GarageProvinceEN
		End Get
		Set
			If (String.Equals(Me._GarageProvinceEN, value) = false) Then
				Me._GarageProvinceEN = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AccidentDate", DbType:="DateTime")>  _
	Public Property AccidentDate() As System.Nullable(Of Date)
		Get
			Return Me._AccidentDate
		End Get
		Set
			If (Me._AccidentDate.Equals(value) = false) Then
				Me._AccidentDate = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Accident_Month", DbType:="DateTime")>  _
	Public Property Accident_Month() As System.Nullable(Of Date)
		Get
			Return Me._Accident_Month
		End Get
		Set
			If (Me._Accident_Month.Equals(value) = false) Then
				Me._Accident_Month = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ClaimGroup", DbType:="Float")>  _
	Public Property ClaimGroup() As System.Nullable(Of Double)
		Get
			Return Me._ClaimGroup
		End Get
		Set
			If (Me._ClaimGroup.Equals(value) = false) Then
				Me._ClaimGroup = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IndemnityGroup", DbType:="Float")>  _
	Public Property IndemnityGroup() As System.Nullable(Of Double)
		Get
			Return Me._IndemnityGroup
		End Get
		Set
			If (Me._IndemnityGroup.Equals(value) = false) Then
				Me._IndemnityGroup = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_No_of_Claim", DbType:="Float")>  _
	Public Property No_of_Claim() As System.Nullable(Of Double)
		Get
			Return Me._No_of_Claim
		End Get
		Set
			If (Me._No_of_Claim.Equals(value) = false) Then
				Me._No_of_Claim = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ClaimCost", DbType:="Float")>  _
	Public Property ClaimCost() As System.Nullable(Of Double)
		Get
			Return Me._ClaimCost
		End Get
		Set
			If (Me._ClaimCost.Equals(value) = false) Then
				Me._ClaimCost = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IndemnityType", DbType:="NVarChar(255)")>  _
	Public Property IndemnityType() As String
		Get
			Return Me._IndemnityType
		End Get
		Set
			If (String.Equals(Me._IndemnityType, value) = false) Then
				Me._IndemnityType = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IndemnityType_E", DbType:="NVarChar(255)")>  _
	Public Property IndemnityType_E() As String
		Get
			Return Me._IndemnityType_E
		End Get
		Set
			If (String.Equals(Me._IndemnityType_E, value) = false) Then
				Me._IndemnityType_E = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_GarageName", DbType:="NVarChar(255)")>  _
	Public Property GarageName() As String
		Get
			Return Me._GarageName
		End Get
		Set
			If (String.Equals(Me._GarageName, value) = false) Then
				Me._GarageName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_GarageType1", DbType:="NVarChar(255)")>  _
	Public Property GarageType1() As String
		Get
			Return Me._GarageType1
		End Get
		Set
			If (String.Equals(Me._GarageType1, value) = false) Then
				Me._GarageType1 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_GarageType2", DbType:="NVarChar(255)")>  _
	Public Property GarageType2() As String
		Get
			Return Me._GarageType2
		End Get
		Set
			If (String.Equals(Me._GarageType2, value) = false) Then
				Me._GarageType2 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_InsurerName", DbType:="NVarChar(255)")>  _
	Public Property InsurerName() As String
		Get
			Return Me._InsurerName
		End Get
		Set
			If (String.Equals(Me._InsurerName, value) = false) Then
				Me._InsurerName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_InsurerCode", DbType:="NVarChar(255)")>  _
	Public Property InsurerCode() As String
		Get
			Return Me._InsurerCode
		End Get
		Set
			If (String.Equals(Me._InsurerCode, value) = false) Then
				Me._InsurerCode = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CustType", DbType:="NVarChar(255)")>  _
	Public Property CustType() As String
		Get
			Return Me._CustType
		End Get
		Set
			If (String.Equals(Me._CustType, value) = false) Then
				Me._CustType = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_App_StartingDate", DbType:="DateTime")>  _
	Public Property App_StartingDate() As System.Nullable(Of Date)
		Get
			Return Me._App_StartingDate
		End Get
		Set
			If (Me._App_StartingDate.Equals(value) = false) Then
				Me._App_StartingDate = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Starting_Month", DbType:="DateTime")>  _
	Public Property Starting_Month() As System.Nullable(Of Date)
		Get
			Return Me._Starting_Month
		End Get
		Set
			If (Me._Starting_Month.Equals(value) = false) Then
				Me._Starting_Month = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Starting_Year", DbType:="NVarChar(255)")>  _
	Public Property Starting_Year() As String
		Get
			Return Me._Starting_Year
		End Get
		Set
			If (String.Equals(Me._Starting_Year, value) = false) Then
				Me._Starting_Year = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_App_EndDate", DbType:="DateTime")>  _
	Public Property App_EndDate() As System.Nullable(Of Date)
		Get
			Return Me._App_EndDate
		End Get
		Set
			If (Me._App_EndDate.Equals(value) = false) Then
				Me._App_EndDate = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_App_ShowroomName", DbType:="NVarChar(255)")>  _
	Public Property App_ShowroomName() As String
		Get
			Return Me._App_ShowroomName
		End Get
		Set
			If (String.Equals(Me._App_ShowroomName, value) = false) Then
				Me._App_ShowroomName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_App_Beneficiary", DbType:="NVarChar(255)")>  _
	Public Property App_Beneficiary() As String
		Get
			Return Me._App_Beneficiary
		End Get
		Set
			If (String.Equals(Me._App_Beneficiary, value) = false) Then
				Me._App_Beneficiary = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_App_Beneficiary_Group", DbType:="NVarChar(255)")>  _
	Public Property App_Beneficiary_Group() As String
		Get
			Return Me._App_Beneficiary_Group
		End Get
		Set
			If (String.Equals(Me._App_Beneficiary_Group, value) = false) Then
				Me._App_Beneficiary_Group = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_App_CarGroup", DbType:="NVarChar(255)")>  _
	Public Property App_CarGroup() As String
		Get
			Return Me._App_CarGroup
		End Get
		Set
			If (String.Equals(Me._App_CarGroup, value) = false) Then
				Me._App_CarGroup = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_App_CarGroup_F", DbType:="NVarChar(255)")>  _
	Public Property App_CarGroup_F() As String
		Get
			Return Me._App_CarGroup_F
		End Get
		Set
			If (String.Equals(Me._App_CarGroup_F, value) = false) Then
				Me._App_CarGroup_F = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_App_CarRegistryYear", DbType:="Float")>  _
	Public Property App_CarRegistryYear() As System.Nullable(Of Double)
		Get
			Return Me._App_CarRegistryYear
		End Get
		Set
			If (Me._App_CarRegistryYear.Equals(value) = false) Then
				Me._App_CarRegistryYear = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Claim_Paid_Month", DbType:="Float")>  _
	Public Property Claim_Paid_Month() As System.Nullable(Of Double)
		Get
			Return Me._Claim_Paid_Month
		End Get
		Set
			If (Me._Claim_Paid_Month.Equals(value) = false) Then
				Me._Claim_Paid_Month = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Claim_Paid_Year", DbType:="Float")>  _
	Public Property Claim_Paid_Year() As System.Nullable(Of Double)
		Get
			Return Me._Claim_Paid_Year
		End Get
		Set
			If (Me._Claim_Paid_Year.Equals(value) = false) Then
				Me._Claim_Paid_Year = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ClaimPaid", DbType:="DateTime")>  _
	Public Property ClaimPaid() As System.Nullable(Of Date)
		Get
			Return Me._ClaimPaid
		End Get
		Set
			If (Me._ClaimPaid.Equals(value) = false) Then
				Me._ClaimPaid = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Accdent_Province", DbType:="NVarChar(255)")>  _
	Public Property Accdent_Province() As String
		Get
			Return Me._Accdent_Province
		End Get
		Set
			If (String.Equals(Me._Accdent_Province, value) = false) Then
				Me._Accdent_Province = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CarAge", DbType:="Int")>  _
	Public Property CarAge() As System.Nullable(Of Integer)
		Get
			Return Me._CarAge
		End Get
		Set
			If (Me._CarAge.Equals(value) = false) Then
				Me._CarAge = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_GarageRegionTH", DbType:="VarChar(50)")>  _
	Public Property GarageRegionTH() As String
		Get
			Return Me._GarageRegionTH
		End Get
		Set
			If (String.Equals(Me._GarageRegionTH, value) = false) Then
				Me._GarageRegionTH = value
			End If
		End Set
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.TblClaimDaily")>  _
Partial Public Class TblClaimDaily
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _AID As Integer
	
	Private _Name As String
	
	Private _SurName As String
	
	Private _YearOfCar As Integer
	
	Private _PolicyNo As String
	
	Private _EngineNo As String
	
	Private _VIN As String
	
	Private _CarNo As String
	
	Private _SumInsurance As Double
	
	Private _StartingDate As Date
	
	Private _Voluntary_NetPremium As Decimal
	
	Private _TempID As String
	
	Private _Status As Integer
	
	Private _IsActive As Integer
	
	Private _ClientCode As String
	
	Private _ClosingDate As Date
	
	Private _ClaimTimes As Integer
	
	Private _No_of_Claim As Double
	
	Private _InsurerName As String
	
	Private _Authorize_Amt As Double
	
	Private _Insurance_Amt As Double
	
	Private _Parts_ordered_from_shop_Amt As Double
	
	Private _BP_Shop_Amt As Double
	
	Private _Consent_Form_Amt As Double
	
	Private _Other_Amt As Double
	
	Private _Authorize As Double
	
	Private _Insurance As Double
	
	Private _Parts_ordered_from_shop As Double
	
	Private _BP_Shop As Double
	
	Private _Consent_Form As Double
	
	Private _Other As Double
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnAIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnAIDChanged()
    End Sub
    Partial Private Sub OnNameChanging(value As String)
    End Sub
    Partial Private Sub OnNameChanged()
    End Sub
    Partial Private Sub OnSurNameChanging(value As String)
    End Sub
    Partial Private Sub OnSurNameChanged()
    End Sub
    Partial Private Sub OnYearOfCarChanging(value As Integer)
    End Sub
    Partial Private Sub OnYearOfCarChanged()
    End Sub
    Partial Private Sub OnPolicyNoChanging(value As String)
    End Sub
    Partial Private Sub OnPolicyNoChanged()
    End Sub
    Partial Private Sub OnEngineNoChanging(value As String)
    End Sub
    Partial Private Sub OnEngineNoChanged()
    End Sub
    Partial Private Sub OnVINChanging(value As String)
    End Sub
    Partial Private Sub OnVINChanged()
    End Sub
    Partial Private Sub OnCarNoChanging(value As String)
    End Sub
    Partial Private Sub OnCarNoChanged()
    End Sub
    Partial Private Sub OnSumInsuranceChanging(value As Double)
    End Sub
    Partial Private Sub OnSumInsuranceChanged()
    End Sub
    Partial Private Sub OnStartingDateChanging(value As Date)
    End Sub
    Partial Private Sub OnStartingDateChanged()
    End Sub
    Partial Private Sub OnVoluntary_NetPremiumChanging(value As Decimal)
    End Sub
    Partial Private Sub OnVoluntary_NetPremiumChanged()
    End Sub
    Partial Private Sub OnTempIDChanging(value As String)
    End Sub
    Partial Private Sub OnTempIDChanged()
    End Sub
    Partial Private Sub OnStatusChanging(value As Integer)
    End Sub
    Partial Private Sub OnStatusChanged()
    End Sub
    Partial Private Sub OnIsActiveChanging(value As Integer)
    End Sub
    Partial Private Sub OnIsActiveChanged()
    End Sub
    Partial Private Sub OnClientCodeChanging(value As String)
    End Sub
    Partial Private Sub OnClientCodeChanged()
    End Sub
    Partial Private Sub OnClosingDateChanging(value As Date)
    End Sub
    Partial Private Sub OnClosingDateChanged()
    End Sub
    Partial Private Sub OnClaimTimesChanging(value As Integer)
    End Sub
    Partial Private Sub OnClaimTimesChanged()
    End Sub
    Partial Private Sub OnNo_of_ClaimChanging(value As Double)
    End Sub
    Partial Private Sub OnNo_of_ClaimChanged()
    End Sub
    Partial Private Sub OnInsurerNameChanging(value As String)
    End Sub
    Partial Private Sub OnInsurerNameChanged()
    End Sub
    Partial Private Sub OnAuthorize_AmtChanging(value As Double)
    End Sub
    Partial Private Sub OnAuthorize_AmtChanged()
    End Sub
    Partial Private Sub OnInsurance_AmtChanging(value As Double)
    End Sub
    Partial Private Sub OnInsurance_AmtChanged()
    End Sub
    Partial Private Sub OnParts_ordered_from_shop_AmtChanging(value As Double)
    End Sub
    Partial Private Sub OnParts_ordered_from_shop_AmtChanged()
    End Sub
    Partial Private Sub OnBP_Shop_AmtChanging(value As Double)
    End Sub
    Partial Private Sub OnBP_Shop_AmtChanged()
    End Sub
    Partial Private Sub OnConsent_Form_AmtChanging(value As Double)
    End Sub
    Partial Private Sub OnConsent_Form_AmtChanged()
    End Sub
    Partial Private Sub OnOther_AmtChanging(value As Double)
    End Sub
    Partial Private Sub OnOther_AmtChanged()
    End Sub
    Partial Private Sub OnAuthorizeChanging(value As Double)
    End Sub
    Partial Private Sub OnAuthorizeChanged()
    End Sub
    Partial Private Sub OnInsuranceChanging(value As Double)
    End Sub
    Partial Private Sub OnInsuranceChanged()
    End Sub
    Partial Private Sub OnParts_ordered_from_shopChanging(value As Double)
    End Sub
    Partial Private Sub OnParts_ordered_from_shopChanged()
    End Sub
    Partial Private Sub OnBP_ShopChanging(value As Double)
    End Sub
    Partial Private Sub OnBP_ShopChanged()
    End Sub
    Partial Private Sub OnConsent_FormChanging(value As Double)
    End Sub
    Partial Private Sub OnConsent_FormChanged()
    End Sub
    Partial Private Sub OnOtherChanging(value As Double)
    End Sub
    Partial Private Sub OnOtherChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AID", DbType:="Int NOT NULL", IsPrimaryKey:=true)>  _
	Public Property AID() As Integer
		Get
			Return Me._AID
		End Get
		Set
			If ((Me._AID = value)  _
						= false) Then
				Me.OnAIDChanging(value)
				Me.SendPropertyChanging
				Me._AID = value
				Me.SendPropertyChanged("AID")
				Me.OnAIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Name", DbType:="VarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property Name() As String
		Get
			Return Me._Name
		End Get
		Set
			If (String.Equals(Me._Name, value) = false) Then
				Me.OnNameChanging(value)
				Me.SendPropertyChanging
				Me._Name = value
				Me.SendPropertyChanged("Name")
				Me.OnNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SurName", DbType:="VarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property SurName() As String
		Get
			Return Me._SurName
		End Get
		Set
			If (String.Equals(Me._SurName, value) = false) Then
				Me.OnSurNameChanging(value)
				Me.SendPropertyChanging
				Me._SurName = value
				Me.SendPropertyChanged("SurName")
				Me.OnSurNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_YearOfCar", DbType:="Int NOT NULL")>  _
	Public Property YearOfCar() As Integer
		Get
			Return Me._YearOfCar
		End Get
		Set
			If ((Me._YearOfCar = value)  _
						= false) Then
				Me.OnYearOfCarChanging(value)
				Me.SendPropertyChanging
				Me._YearOfCar = value
				Me.SendPropertyChanged("YearOfCar")
				Me.OnYearOfCarChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PolicyNo", DbType:="VarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property PolicyNo() As String
		Get
			Return Me._PolicyNo
		End Get
		Set
			If (String.Equals(Me._PolicyNo, value) = false) Then
				Me.OnPolicyNoChanging(value)
				Me.SendPropertyChanging
				Me._PolicyNo = value
				Me.SendPropertyChanged("PolicyNo")
				Me.OnPolicyNoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EngineNo", DbType:="NVarChar(255) NOT NULL", CanBeNull:=false)>  _
	Public Property EngineNo() As String
		Get
			Return Me._EngineNo
		End Get
		Set
			If (String.Equals(Me._EngineNo, value) = false) Then
				Me.OnEngineNoChanging(value)
				Me.SendPropertyChanging
				Me._EngineNo = value
				Me.SendPropertyChanged("EngineNo")
				Me.OnEngineNoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_VIN", DbType:="VarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property VIN() As String
		Get
			Return Me._VIN
		End Get
		Set
			If (String.Equals(Me._VIN, value) = false) Then
				Me.OnVINChanging(value)
				Me.SendPropertyChanging
				Me._VIN = value
				Me.SendPropertyChanged("VIN")
				Me.OnVINChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CarNo", DbType:="NVarChar(255) NOT NULL", CanBeNull:=false)>  _
	Public Property CarNo() As String
		Get
			Return Me._CarNo
		End Get
		Set
			If (String.Equals(Me._CarNo, value) = false) Then
				Me.OnCarNoChanging(value)
				Me.SendPropertyChanging
				Me._CarNo = value
				Me.SendPropertyChanged("CarNo")
				Me.OnCarNoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SumInsurance", DbType:="Float NOT NULL")>  _
	Public Property SumInsurance() As Double
		Get
			Return Me._SumInsurance
		End Get
		Set
			If ((Me._SumInsurance = value)  _
						= false) Then
				Me.OnSumInsuranceChanging(value)
				Me.SendPropertyChanging
				Me._SumInsurance = value
				Me.SendPropertyChanged("SumInsurance")
				Me.OnSumInsuranceChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_StartingDate", DbType:="DateTime NOT NULL")>  _
	Public Property StartingDate() As Date
		Get
			Return Me._StartingDate
		End Get
		Set
			If ((Me._StartingDate = value)  _
						= false) Then
				Me.OnStartingDateChanging(value)
				Me.SendPropertyChanging
				Me._StartingDate = value
				Me.SendPropertyChanged("StartingDate")
				Me.OnStartingDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Voluntary_NetPremium", DbType:="Decimal(18,2) NOT NULL")>  _
	Public Property Voluntary_NetPremium() As Decimal
		Get
			Return Me._Voluntary_NetPremium
		End Get
		Set
			If ((Me._Voluntary_NetPremium = value)  _
						= false) Then
				Me.OnVoluntary_NetPremiumChanging(value)
				Me.SendPropertyChanging
				Me._Voluntary_NetPremium = value
				Me.SendPropertyChanged("Voluntary_NetPremium")
				Me.OnVoluntary_NetPremiumChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TempID", DbType:="VarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property TempID() As String
		Get
			Return Me._TempID
		End Get
		Set
			If (String.Equals(Me._TempID, value) = false) Then
				Me.OnTempIDChanging(value)
				Me.SendPropertyChanging
				Me._TempID = value
				Me.SendPropertyChanged("TempID")
				Me.OnTempIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Status", DbType:="Int NOT NULL")>  _
	Public Property Status() As Integer
		Get
			Return Me._Status
		End Get
		Set
			If ((Me._Status = value)  _
						= false) Then
				Me.OnStatusChanging(value)
				Me.SendPropertyChanging
				Me._Status = value
				Me.SendPropertyChanged("Status")
				Me.OnStatusChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IsActive", DbType:="Int NOT NULL")>  _
	Public Property IsActive() As Integer
		Get
			Return Me._IsActive
		End Get
		Set
			If ((Me._IsActive = value)  _
						= false) Then
				Me.OnIsActiveChanging(value)
				Me.SendPropertyChanging
				Me._IsActive = value
				Me.SendPropertyChanged("IsActive")
				Me.OnIsActiveChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ClientCode", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property ClientCode() As String
		Get
			Return Me._ClientCode
		End Get
		Set
			If (String.Equals(Me._ClientCode, value) = false) Then
				Me.OnClientCodeChanging(value)
				Me.SendPropertyChanging
				Me._ClientCode = value
				Me.SendPropertyChanged("ClientCode")
				Me.OnClientCodeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ClosingDate", DbType:="DateTime NOT NULL")>  _
	Public Property ClosingDate() As Date
		Get
			Return Me._ClosingDate
		End Get
		Set
			If ((Me._ClosingDate = value)  _
						= false) Then
				Me.OnClosingDateChanging(value)
				Me.SendPropertyChanging
				Me._ClosingDate = value
				Me.SendPropertyChanged("ClosingDate")
				Me.OnClosingDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ClaimTimes", DbType:="Int NOT NULL")>  _
	Public Property ClaimTimes() As Integer
		Get
			Return Me._ClaimTimes
		End Get
		Set
			If ((Me._ClaimTimes = value)  _
						= false) Then
				Me.OnClaimTimesChanging(value)
				Me.SendPropertyChanging
				Me._ClaimTimes = value
				Me.SendPropertyChanged("ClaimTimes")
				Me.OnClaimTimesChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_No_of_Claim", DbType:="Float NOT NULL")>  _
	Public Property No_of_Claim() As Double
		Get
			Return Me._No_of_Claim
		End Get
		Set
			If ((Me._No_of_Claim = value)  _
						= false) Then
				Me.OnNo_of_ClaimChanging(value)
				Me.SendPropertyChanging
				Me._No_of_Claim = value
				Me.SendPropertyChanged("No_of_Claim")
				Me.OnNo_of_ClaimChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_InsurerName", DbType:="NVarChar(255) NOT NULL", CanBeNull:=false)>  _
	Public Property InsurerName() As String
		Get
			Return Me._InsurerName
		End Get
		Set
			If (String.Equals(Me._InsurerName, value) = false) Then
				Me.OnInsurerNameChanging(value)
				Me.SendPropertyChanging
				Me._InsurerName = value
				Me.SendPropertyChanged("InsurerName")
				Me.OnInsurerNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Authorize_Amt", DbType:="Float NOT NULL")>  _
	Public Property Authorize_Amt() As Double
		Get
			Return Me._Authorize_Amt
		End Get
		Set
			If ((Me._Authorize_Amt = value)  _
						= false) Then
				Me.OnAuthorize_AmtChanging(value)
				Me.SendPropertyChanging
				Me._Authorize_Amt = value
				Me.SendPropertyChanged("Authorize_Amt")
				Me.OnAuthorize_AmtChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Insurance_Amt", DbType:="Float NOT NULL")>  _
	Public Property Insurance_Amt() As Double
		Get
			Return Me._Insurance_Amt
		End Get
		Set
			If ((Me._Insurance_Amt = value)  _
						= false) Then
				Me.OnInsurance_AmtChanging(value)
				Me.SendPropertyChanging
				Me._Insurance_Amt = value
				Me.SendPropertyChanged("Insurance_Amt")
				Me.OnInsurance_AmtChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[Parts ordered from shop Amt]", Storage:="_Parts_ordered_from_shop_Amt", DbType:="Float NOT NULL")>  _
	Public Property Parts_ordered_from_shop_Amt() As Double
		Get
			Return Me._Parts_ordered_from_shop_Amt
		End Get
		Set
			If ((Me._Parts_ordered_from_shop_Amt = value)  _
						= false) Then
				Me.OnParts_ordered_from_shop_AmtChanging(value)
				Me.SendPropertyChanging
				Me._Parts_ordered_from_shop_Amt = value
				Me.SendPropertyChanged("Parts_ordered_from_shop_Amt")
				Me.OnParts_ordered_from_shop_AmtChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[BP Shop Amt]", Storage:="_BP_Shop_Amt", DbType:="Float NOT NULL")>  _
	Public Property BP_Shop_Amt() As Double
		Get
			Return Me._BP_Shop_Amt
		End Get
		Set
			If ((Me._BP_Shop_Amt = value)  _
						= false) Then
				Me.OnBP_Shop_AmtChanging(value)
				Me.SendPropertyChanging
				Me._BP_Shop_Amt = value
				Me.SendPropertyChanged("BP_Shop_Amt")
				Me.OnBP_Shop_AmtChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[Consent Form Amt]", Storage:="_Consent_Form_Amt", DbType:="Float NOT NULL")>  _
	Public Property Consent_Form_Amt() As Double
		Get
			Return Me._Consent_Form_Amt
		End Get
		Set
			If ((Me._Consent_Form_Amt = value)  _
						= false) Then
				Me.OnConsent_Form_AmtChanging(value)
				Me.SendPropertyChanging
				Me._Consent_Form_Amt = value
				Me.SendPropertyChanged("Consent_Form_Amt")
				Me.OnConsent_Form_AmtChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[Other Amt]", Storage:="_Other_Amt", DbType:="Float NOT NULL")>  _
	Public Property Other_Amt() As Double
		Get
			Return Me._Other_Amt
		End Get
		Set
			If ((Me._Other_Amt = value)  _
						= false) Then
				Me.OnOther_AmtChanging(value)
				Me.SendPropertyChanging
				Me._Other_Amt = value
				Me.SendPropertyChanged("Other_Amt")
				Me.OnOther_AmtChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Authorize", DbType:="Float NOT NULL")>  _
	Public Property Authorize() As Double
		Get
			Return Me._Authorize
		End Get
		Set
			If ((Me._Authorize = value)  _
						= false) Then
				Me.OnAuthorizeChanging(value)
				Me.SendPropertyChanging
				Me._Authorize = value
				Me.SendPropertyChanged("Authorize")
				Me.OnAuthorizeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Insurance", DbType:="Float NOT NULL")>  _
	Public Property Insurance() As Double
		Get
			Return Me._Insurance
		End Get
		Set
			If ((Me._Insurance = value)  _
						= false) Then
				Me.OnInsuranceChanging(value)
				Me.SendPropertyChanging
				Me._Insurance = value
				Me.SendPropertyChanged("Insurance")
				Me.OnInsuranceChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[Parts ordered from shop]", Storage:="_Parts_ordered_from_shop", DbType:="Float NOT NULL")>  _
	Public Property Parts_ordered_from_shop() As Double
		Get
			Return Me._Parts_ordered_from_shop
		End Get
		Set
			If ((Me._Parts_ordered_from_shop = value)  _
						= false) Then
				Me.OnParts_ordered_from_shopChanging(value)
				Me.SendPropertyChanging
				Me._Parts_ordered_from_shop = value
				Me.SendPropertyChanged("Parts_ordered_from_shop")
				Me.OnParts_ordered_from_shopChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[BP Shop]", Storage:="_BP_Shop", DbType:="Float NOT NULL")>  _
	Public Property BP_Shop() As Double
		Get
			Return Me._BP_Shop
		End Get
		Set
			If ((Me._BP_Shop = value)  _
						= false) Then
				Me.OnBP_ShopChanging(value)
				Me.SendPropertyChanging
				Me._BP_Shop = value
				Me.SendPropertyChanged("BP_Shop")
				Me.OnBP_ShopChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[Consent Form]", Storage:="_Consent_Form", DbType:="Float NOT NULL")>  _
	Public Property Consent_Form() As Double
		Get
			Return Me._Consent_Form
		End Get
		Set
			If ((Me._Consent_Form = value)  _
						= false) Then
				Me.OnConsent_FormChanging(value)
				Me.SendPropertyChanging
				Me._Consent_Form = value
				Me.SendPropertyChanged("Consent_Form")
				Me.OnConsent_FormChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Other", DbType:="Float NOT NULL")>  _
	Public Property Other() As Double
		Get
			Return Me._Other
		End Get
		Set
			If ((Me._Other = value)  _
						= false) Then
				Me.OnOtherChanging(value)
				Me.SendPropertyChanging
				Me._Other = value
				Me.SendPropertyChanged("Other")
				Me.OnOtherChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
