'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="LWTReports")>  _
Partial Public Class DataClasses_LWTReportsDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertV_Nissan(instance As V_Nissan)
    End Sub
  Partial Private Sub UpdateV_Nissan(instance As V_Nissan)
    End Sub
  Partial Private Sub DeleteV_Nissan(instance As V_Nissan)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings("LWTReportsConnectionString").ConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property V_Nissans() As System.Data.Linq.Table(Of V_Nissan)
		Get
			Return Me.GetTable(Of V_Nissan)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.V_Nissan")>  _
Partial Public Class V_Nissan
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _AppID As Integer
	
	Private _TempID As String
	
	Private _CusName As String
	
	Private _CusSurname As String
	
	Private _CusIDCard As String
	
	Private _CusAddress1 As String
	
	Private _CusAddress2 As String
	
	Private _CusMobile As String
	
	Private _CusHomePhone As String
	
	Private _CusOfficePhone As System.Nullable(Of Integer)
	
	Private _CarEngineNo As String
	
	Private _CarChassisNo As String
	
	Private _CarPlantNo As String
	
	Private _DateEffective As System.Nullable(Of Date)
	
	Private _DateExpired As System.Nullable(Of Date)
	
	Private _DateNotification As System.Nullable(Of Date)
	
	Private _AppStatus As Integer
	
	Private _AppIsActive As System.Nullable(Of Integer)
	
	Private _ClientCode As String
	
	Private _CmiBuying As System.Nullable(Of Integer)
	
	Private _AppBeneficiary As String
	
	Private _LeasingID As System.Nullable(Of Integer)
	
	Private _ClosingDate As System.Nullable(Of Date)
	
	Private _ClosingMonth As System.Nullable(Of Date)
	
	Private _ClosingDay As System.Nullable(Of Date)
	
	Private _AppStatusRecived As System.Nullable(Of Boolean)
	
	Private _ProjectID As System.Nullable(Of Integer)
	
	Private _NotifyName As String
	
	Private _CusTitle As String
	
	Private _CarGroupID As System.Nullable(Of Integer)
	
	Private _CarGroupName As String
	
	Private _CarBrandName As String
	
	Private _CarModelName As String
	
	Private _CarTypeName As String
	
	Private _CarTypeNameFull As String
	
	Private _CarModelCode As String
	
	Private _CarGroupNameM2 As String
	
	Private _DealerNameEn As String
	
	Private _NLTDealerCode As String
	
	Private _NLTArea As String
	
	Private _InsurerNameTh As String
	
	Private _InsurerCodeSibis As String
	
	Private _InsurerNameEn As String
	
	Private _InsurerCode As String
	
	Private _LeasID As System.Nullable(Of Integer)
	
	Private _LeasName As String
	
	Private _LeasNameAbbr As String
	
	Private _LeasNameShort As String
	
	Private _ModelNameM2 As String
	
	Private _NLTBookingDate As System.Nullable(Of Date)
	
	Private _SchemeCode As String
	
	Private _VmiNetPremium As System.Nullable(Of Decimal)
	
	Private _VmiStamp As System.Nullable(Of Decimal)
	
	Private _VmiVat As System.Nullable(Of Decimal)
	
	Private _VmiTotalPremium As System.Nullable(Of Decimal)
	
	Private _CmiNetPremium As System.Nullable(Of Decimal)
	
	Private _CmiStamp As System.Nullable(Of Decimal)
	
	Private _CmiVat As System.Nullable(Of Decimal)
	
	Private _CmiTotalPremium As System.Nullable(Of Decimal)
	
	Private _ClassOfRiskVMI As String
	
	Private _ClassOfRiskCMI As String
	
	Private _ShowroomID As System.Nullable(Of Integer)
	
	Private _ShowroomName As String
	
	Private _DealerID As System.Nullable(Of Integer)
	
	Private _ShorwoomNameEn As String
	
	Private _CarTypeNameM2 As String
	
	Private _TypeInsID As System.Nullable(Of Integer)
	
	Private _TypeInsName As String
	
	Private _TypeInsStatus As System.Nullable(Of Integer)
	
	Private _TypeInsReportToNLTH As System.Nullable(Of Boolean)
	
	Private _TypeInsIsFree As System.Nullable(Of Boolean)
	
	Private _UserAddedTel As String
	
	Private _UserAddedType As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnAppIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnAppIDChanged()
    End Sub
    Partial Private Sub OnTempIDChanging(value As String)
    End Sub
    Partial Private Sub OnTempIDChanged()
    End Sub
    Partial Private Sub OnCusNameChanging(value As String)
    End Sub
    Partial Private Sub OnCusNameChanged()
    End Sub
    Partial Private Sub OnCusSurnameChanging(value As String)
    End Sub
    Partial Private Sub OnCusSurnameChanged()
    End Sub
    Partial Private Sub OnCusIDCardChanging(value As String)
    End Sub
    Partial Private Sub OnCusIDCardChanged()
    End Sub
    Partial Private Sub OnCusAddress1Changing(value As String)
    End Sub
    Partial Private Sub OnCusAddress1Changed()
    End Sub
    Partial Private Sub OnCusAddress2Changing(value As String)
    End Sub
    Partial Private Sub OnCusAddress2Changed()
    End Sub
    Partial Private Sub OnCusMobileChanging(value As String)
    End Sub
    Partial Private Sub OnCusMobileChanged()
    End Sub
    Partial Private Sub OnCusHomePhoneChanging(value As String)
    End Sub
    Partial Private Sub OnCusHomePhoneChanged()
    End Sub
    Partial Private Sub OnCusOfficePhoneChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnCusOfficePhoneChanged()
    End Sub
    Partial Private Sub OnCarEngineNoChanging(value As String)
    End Sub
    Partial Private Sub OnCarEngineNoChanged()
    End Sub
    Partial Private Sub OnCarChassisNoChanging(value As String)
    End Sub
    Partial Private Sub OnCarChassisNoChanged()
    End Sub
    Partial Private Sub OnCarPlantNoChanging(value As String)
    End Sub
    Partial Private Sub OnCarPlantNoChanged()
    End Sub
    Partial Private Sub OnDateEffectiveChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnDateEffectiveChanged()
    End Sub
    Partial Private Sub OnDateExpiredChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnDateExpiredChanged()
    End Sub
    Partial Private Sub OnDateNotificationChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnDateNotificationChanged()
    End Sub
    Partial Private Sub OnAppStatusChanging(value As Integer)
    End Sub
    Partial Private Sub OnAppStatusChanged()
    End Sub
    Partial Private Sub OnAppIsActiveChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnAppIsActiveChanged()
    End Sub
    Partial Private Sub OnClientCodeChanging(value As String)
    End Sub
    Partial Private Sub OnClientCodeChanged()
    End Sub
    Partial Private Sub OnCmiBuyingChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnCmiBuyingChanged()
    End Sub
    Partial Private Sub OnAppBeneficiaryChanging(value As String)
    End Sub
    Partial Private Sub OnAppBeneficiaryChanged()
    End Sub
    Partial Private Sub OnLeasingIDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnLeasingIDChanged()
    End Sub
    Partial Private Sub OnClosingDateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnClosingDateChanged()
    End Sub
    Partial Private Sub OnClosingMonthChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnClosingMonthChanged()
    End Sub
    Partial Private Sub OnClosingDayChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnClosingDayChanged()
    End Sub
    Partial Private Sub OnAppStatusRecivedChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnAppStatusRecivedChanged()
    End Sub
    Partial Private Sub OnProjectIDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnProjectIDChanged()
    End Sub
    Partial Private Sub OnNotifyNameChanging(value As String)
    End Sub
    Partial Private Sub OnNotifyNameChanged()
    End Sub
    Partial Private Sub OnCusTitleChanging(value As String)
    End Sub
    Partial Private Sub OnCusTitleChanged()
    End Sub
    Partial Private Sub OnCarGroupIDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnCarGroupIDChanged()
    End Sub
    Partial Private Sub OnCarGroupNameChanging(value As String)
    End Sub
    Partial Private Sub OnCarGroupNameChanged()
    End Sub
    Partial Private Sub OnCarBrandNameChanging(value As String)
    End Sub
    Partial Private Sub OnCarBrandNameChanged()
    End Sub
    Partial Private Sub OnCarModelNameChanging(value As String)
    End Sub
    Partial Private Sub OnCarModelNameChanged()
    End Sub
    Partial Private Sub OnCarTypeNameChanging(value As String)
    End Sub
    Partial Private Sub OnCarTypeNameChanged()
    End Sub
    Partial Private Sub OnCarTypeNameFullChanging(value As String)
    End Sub
    Partial Private Sub OnCarTypeNameFullChanged()
    End Sub
    Partial Private Sub OnCarModelCodeChanging(value As String)
    End Sub
    Partial Private Sub OnCarModelCodeChanged()
    End Sub
    Partial Private Sub OnCarGroupNameM2Changing(value As String)
    End Sub
    Partial Private Sub OnCarGroupNameM2Changed()
    End Sub
    Partial Private Sub OnDealerNameEnChanging(value As String)
    End Sub
    Partial Private Sub OnDealerNameEnChanged()
    End Sub
    Partial Private Sub OnNLTDealerCodeChanging(value As String)
    End Sub
    Partial Private Sub OnNLTDealerCodeChanged()
    End Sub
    Partial Private Sub OnNLTAreaChanging(value As String)
    End Sub
    Partial Private Sub OnNLTAreaChanged()
    End Sub
    Partial Private Sub OnInsurerNameThChanging(value As String)
    End Sub
    Partial Private Sub OnInsurerNameThChanged()
    End Sub
    Partial Private Sub OnInsurerCodeSibisChanging(value As String)
    End Sub
    Partial Private Sub OnInsurerCodeSibisChanged()
    End Sub
    Partial Private Sub OnInsurerNameEnChanging(value As String)
    End Sub
    Partial Private Sub OnInsurerNameEnChanged()
    End Sub
    Partial Private Sub OnInsurerCodeChanging(value As String)
    End Sub
    Partial Private Sub OnInsurerCodeChanged()
    End Sub
    Partial Private Sub OnLeasIDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnLeasIDChanged()
    End Sub
    Partial Private Sub OnLeasNameChanging(value As String)
    End Sub
    Partial Private Sub OnLeasNameChanged()
    End Sub
    Partial Private Sub OnLeasNameAbbrChanging(value As String)
    End Sub
    Partial Private Sub OnLeasNameAbbrChanged()
    End Sub
    Partial Private Sub OnLeasNameShortChanging(value As String)
    End Sub
    Partial Private Sub OnLeasNameShortChanged()
    End Sub
    Partial Private Sub OnModelNameM2Changing(value As String)
    End Sub
    Partial Private Sub OnModelNameM2Changed()
    End Sub
    Partial Private Sub OnNLTBookingDateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnNLTBookingDateChanged()
    End Sub
    Partial Private Sub OnSchemeCodeChanging(value As String)
    End Sub
    Partial Private Sub OnSchemeCodeChanged()
    End Sub
    Partial Private Sub OnVmiNetPremiumChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnVmiNetPremiumChanged()
    End Sub
    Partial Private Sub OnVmiStampChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnVmiStampChanged()
    End Sub
    Partial Private Sub OnVmiVatChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnVmiVatChanged()
    End Sub
    Partial Private Sub OnVmiTotalPremiumChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnVmiTotalPremiumChanged()
    End Sub
    Partial Private Sub OnCmiNetPremiumChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnCmiNetPremiumChanged()
    End Sub
    Partial Private Sub OnCmiStampChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnCmiStampChanged()
    End Sub
    Partial Private Sub OnCmiVatChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnCmiVatChanged()
    End Sub
    Partial Private Sub OnCmiTotalPremiumChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnCmiTotalPremiumChanged()
    End Sub
    Partial Private Sub OnClassOfRiskVMIChanging(value As String)
    End Sub
    Partial Private Sub OnClassOfRiskVMIChanged()
    End Sub
    Partial Private Sub OnClassOfRiskCMIChanging(value As String)
    End Sub
    Partial Private Sub OnClassOfRiskCMIChanged()
    End Sub
    Partial Private Sub OnShowroomIDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnShowroomIDChanged()
    End Sub
    Partial Private Sub OnShowroomNameChanging(value As String)
    End Sub
    Partial Private Sub OnShowroomNameChanged()
    End Sub
    Partial Private Sub OnDealerIDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnDealerIDChanged()
    End Sub
    Partial Private Sub OnShorwoomNameEnChanging(value As String)
    End Sub
    Partial Private Sub OnShorwoomNameEnChanged()
    End Sub
    Partial Private Sub OnCarTypeNameM2Changing(value As String)
    End Sub
    Partial Private Sub OnCarTypeNameM2Changed()
    End Sub
    Partial Private Sub OnTypeInsIDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnTypeInsIDChanged()
    End Sub
    Partial Private Sub OnTypeInsNameChanging(value As String)
    End Sub
    Partial Private Sub OnTypeInsNameChanged()
    End Sub
    Partial Private Sub OnTypeInsStatusChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnTypeInsStatusChanged()
    End Sub
    Partial Private Sub OnTypeInsReportToNLTHChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnTypeInsReportToNLTHChanged()
    End Sub
    Partial Private Sub OnTypeInsIsFreeChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnTypeInsIsFreeChanged()
    End Sub
    Partial Private Sub OnUserAddedTelChanging(value As String)
    End Sub
    Partial Private Sub OnUserAddedTelChanged()
    End Sub
    Partial Private Sub OnUserAddedTypeChanging(value As String)
    End Sub
    Partial Private Sub OnUserAddedTypeChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AppID", DbType:="Int NOT NULL", IsPrimaryKey:=true)>  _
	Public Property AppID() As Integer
		Get
			Return Me._AppID
		End Get
		Set
			If ((Me._AppID = value)  _
						= false) Then
				Me.OnAppIDChanging(value)
				Me.SendPropertyChanging
				Me._AppID = value
				Me.SendPropertyChanged("AppID")
				Me.OnAppIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TempID", DbType:="VarChar(50)")>  _
	Public Property TempID() As String
		Get
			Return Me._TempID
		End Get
		Set
			If (String.Equals(Me._TempID, value) = false) Then
				Me.OnTempIDChanging(value)
				Me.SendPropertyChanging
				Me._TempID = value
				Me.SendPropertyChanged("TempID")
				Me.OnTempIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CusName", DbType:="VarChar(50)")>  _
	Public Property CusName() As String
		Get
			Return Me._CusName
		End Get
		Set
			If (String.Equals(Me._CusName, value) = false) Then
				Me.OnCusNameChanging(value)
				Me.SendPropertyChanging
				Me._CusName = value
				Me.SendPropertyChanged("CusName")
				Me.OnCusNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CusSurname", DbType:="VarChar(50)")>  _
	Public Property CusSurname() As String
		Get
			Return Me._CusSurname
		End Get
		Set
			If (String.Equals(Me._CusSurname, value) = false) Then
				Me.OnCusSurnameChanging(value)
				Me.SendPropertyChanging
				Me._CusSurname = value
				Me.SendPropertyChanged("CusSurname")
				Me.OnCusSurnameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CusIDCard", DbType:="VarChar(50)")>  _
	Public Property CusIDCard() As String
		Get
			Return Me._CusIDCard
		End Get
		Set
			If (String.Equals(Me._CusIDCard, value) = false) Then
				Me.OnCusIDCardChanging(value)
				Me.SendPropertyChanging
				Me._CusIDCard = value
				Me.SendPropertyChanged("CusIDCard")
				Me.OnCusIDCardChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CusAddress1", DbType:="NVarChar(255)")>  _
	Public Property CusAddress1() As String
		Get
			Return Me._CusAddress1
		End Get
		Set
			If (String.Equals(Me._CusAddress1, value) = false) Then
				Me.OnCusAddress1Changing(value)
				Me.SendPropertyChanging
				Me._CusAddress1 = value
				Me.SendPropertyChanged("CusAddress1")
				Me.OnCusAddress1Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CusAddress2", DbType:="NVarChar(255)")>  _
	Public Property CusAddress2() As String
		Get
			Return Me._CusAddress2
		End Get
		Set
			If (String.Equals(Me._CusAddress2, value) = false) Then
				Me.OnCusAddress2Changing(value)
				Me.SendPropertyChanging
				Me._CusAddress2 = value
				Me.SendPropertyChanged("CusAddress2")
				Me.OnCusAddress2Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CusMobile", DbType:="VarChar(50)")>  _
	Public Property CusMobile() As String
		Get
			Return Me._CusMobile
		End Get
		Set
			If (String.Equals(Me._CusMobile, value) = false) Then
				Me.OnCusMobileChanging(value)
				Me.SendPropertyChanging
				Me._CusMobile = value
				Me.SendPropertyChanged("CusMobile")
				Me.OnCusMobileChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CusHomePhone", DbType:="VarChar(50)")>  _
	Public Property CusHomePhone() As String
		Get
			Return Me._CusHomePhone
		End Get
		Set
			If (String.Equals(Me._CusHomePhone, value) = false) Then
				Me.OnCusHomePhoneChanging(value)
				Me.SendPropertyChanging
				Me._CusHomePhone = value
				Me.SendPropertyChanged("CusHomePhone")
				Me.OnCusHomePhoneChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CusOfficePhone", DbType:="Int")>  _
	Public Property CusOfficePhone() As System.Nullable(Of Integer)
		Get
			Return Me._CusOfficePhone
		End Get
		Set
			If (Me._CusOfficePhone.Equals(value) = false) Then
				Me.OnCusOfficePhoneChanging(value)
				Me.SendPropertyChanging
				Me._CusOfficePhone = value
				Me.SendPropertyChanged("CusOfficePhone")
				Me.OnCusOfficePhoneChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CarEngineNo", DbType:="NVarChar(255)")>  _
	Public Property CarEngineNo() As String
		Get
			Return Me._CarEngineNo
		End Get
		Set
			If (String.Equals(Me._CarEngineNo, value) = false) Then
				Me.OnCarEngineNoChanging(value)
				Me.SendPropertyChanging
				Me._CarEngineNo = value
				Me.SendPropertyChanged("CarEngineNo")
				Me.OnCarEngineNoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CarChassisNo", DbType:="VarChar(50)")>  _
	Public Property CarChassisNo() As String
		Get
			Return Me._CarChassisNo
		End Get
		Set
			If (String.Equals(Me._CarChassisNo, value) = false) Then
				Me.OnCarChassisNoChanging(value)
				Me.SendPropertyChanging
				Me._CarChassisNo = value
				Me.SendPropertyChanged("CarChassisNo")
				Me.OnCarChassisNoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CarPlantNo", DbType:="NVarChar(255)")>  _
	Public Property CarPlantNo() As String
		Get
			Return Me._CarPlantNo
		End Get
		Set
			If (String.Equals(Me._CarPlantNo, value) = false) Then
				Me.OnCarPlantNoChanging(value)
				Me.SendPropertyChanging
				Me._CarPlantNo = value
				Me.SendPropertyChanged("CarPlantNo")
				Me.OnCarPlantNoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DateEffective", DbType:="DateTime")>  _
	Public Property DateEffective() As System.Nullable(Of Date)
		Get
			Return Me._DateEffective
		End Get
		Set
			If (Me._DateEffective.Equals(value) = false) Then
				Me.OnDateEffectiveChanging(value)
				Me.SendPropertyChanging
				Me._DateEffective = value
				Me.SendPropertyChanged("DateEffective")
				Me.OnDateEffectiveChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DateExpired", DbType:="DateTime")>  _
	Public Property DateExpired() As System.Nullable(Of Date)
		Get
			Return Me._DateExpired
		End Get
		Set
			If (Me._DateExpired.Equals(value) = false) Then
				Me.OnDateExpiredChanging(value)
				Me.SendPropertyChanging
				Me._DateExpired = value
				Me.SendPropertyChanged("DateExpired")
				Me.OnDateExpiredChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DateNotification", DbType:="DateTime")>  _
	Public Property DateNotification() As System.Nullable(Of Date)
		Get
			Return Me._DateNotification
		End Get
		Set
			If (Me._DateNotification.Equals(value) = false) Then
				Me.OnDateNotificationChanging(value)
				Me.SendPropertyChanging
				Me._DateNotification = value
				Me.SendPropertyChanged("DateNotification")
				Me.OnDateNotificationChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AppStatus", DbType:="Int NOT NULL")>  _
	Public Property AppStatus() As Integer
		Get
			Return Me._AppStatus
		End Get
		Set
			If ((Me._AppStatus = value)  _
						= false) Then
				Me.OnAppStatusChanging(value)
				Me.SendPropertyChanging
				Me._AppStatus = value
				Me.SendPropertyChanged("AppStatus")
				Me.OnAppStatusChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AppIsActive", DbType:="Int")>  _
	Public Property AppIsActive() As System.Nullable(Of Integer)
		Get
			Return Me._AppIsActive
		End Get
		Set
			If (Me._AppIsActive.Equals(value) = false) Then
				Me.OnAppIsActiveChanging(value)
				Me.SendPropertyChanging
				Me._AppIsActive = value
				Me.SendPropertyChanged("AppIsActive")
				Me.OnAppIsActiveChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ClientCode", DbType:="NVarChar(50)")>  _
	Public Property ClientCode() As String
		Get
			Return Me._ClientCode
		End Get
		Set
			If (String.Equals(Me._ClientCode, value) = false) Then
				Me.OnClientCodeChanging(value)
				Me.SendPropertyChanging
				Me._ClientCode = value
				Me.SendPropertyChanged("ClientCode")
				Me.OnClientCodeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CmiBuying", DbType:="Int")>  _
	Public Property CmiBuying() As System.Nullable(Of Integer)
		Get
			Return Me._CmiBuying
		End Get
		Set
			If (Me._CmiBuying.Equals(value) = false) Then
				Me.OnCmiBuyingChanging(value)
				Me.SendPropertyChanging
				Me._CmiBuying = value
				Me.SendPropertyChanged("CmiBuying")
				Me.OnCmiBuyingChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AppBeneficiary", DbType:="NVarChar(100)")>  _
	Public Property AppBeneficiary() As String
		Get
			Return Me._AppBeneficiary
		End Get
		Set
			If (String.Equals(Me._AppBeneficiary, value) = false) Then
				Me.OnAppBeneficiaryChanging(value)
				Me.SendPropertyChanging
				Me._AppBeneficiary = value
				Me.SendPropertyChanged("AppBeneficiary")
				Me.OnAppBeneficiaryChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LeasingID", DbType:="Int")>  _
	Public Property LeasingID() As System.Nullable(Of Integer)
		Get
			Return Me._LeasingID
		End Get
		Set
			If (Me._LeasingID.Equals(value) = false) Then
				Me.OnLeasingIDChanging(value)
				Me.SendPropertyChanging
				Me._LeasingID = value
				Me.SendPropertyChanged("LeasingID")
				Me.OnLeasingIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ClosingDate", DbType:="DateTime")>  _
	Public Property ClosingDate() As System.Nullable(Of Date)
		Get
			Return Me._ClosingDate
		End Get
		Set
			If (Me._ClosingDate.Equals(value) = false) Then
				Me.OnClosingDateChanging(value)
				Me.SendPropertyChanging
				Me._ClosingDate = value
				Me.SendPropertyChanged("ClosingDate")
				Me.OnClosingDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ClosingMonth", DbType:="DateTime")>  _
	Public Property ClosingMonth() As System.Nullable(Of Date)
		Get
			Return Me._ClosingMonth
		End Get
		Set
			If (Me._ClosingMonth.Equals(value) = false) Then
				Me.OnClosingMonthChanging(value)
				Me.SendPropertyChanging
				Me._ClosingMonth = value
				Me.SendPropertyChanged("ClosingMonth")
				Me.OnClosingMonthChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ClosingDay", DbType:="DateTime")>  _
	Public Property ClosingDay() As System.Nullable(Of Date)
		Get
			Return Me._ClosingDay
		End Get
		Set
			If (Me._ClosingDay.Equals(value) = false) Then
				Me.OnClosingDayChanging(value)
				Me.SendPropertyChanging
				Me._ClosingDay = value
				Me.SendPropertyChanged("ClosingDay")
				Me.OnClosingDayChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AppStatusRecived", DbType:="Bit")>  _
	Public Property AppStatusRecived() As System.Nullable(Of Boolean)
		Get
			Return Me._AppStatusRecived
		End Get
		Set
			If (Me._AppStatusRecived.Equals(value) = false) Then
				Me.OnAppStatusRecivedChanging(value)
				Me.SendPropertyChanging
				Me._AppStatusRecived = value
				Me.SendPropertyChanged("AppStatusRecived")
				Me.OnAppStatusRecivedChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ProjectID", DbType:="Int")>  _
	Public Property ProjectID() As System.Nullable(Of Integer)
		Get
			Return Me._ProjectID
		End Get
		Set
			If (Me._ProjectID.Equals(value) = false) Then
				Me.OnProjectIDChanging(value)
				Me.SendPropertyChanging
				Me._ProjectID = value
				Me.SendPropertyChanged("ProjectID")
				Me.OnProjectIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NotifyName", DbType:="VarChar(50)")>  _
	Public Property NotifyName() As String
		Get
			Return Me._NotifyName
		End Get
		Set
			If (String.Equals(Me._NotifyName, value) = false) Then
				Me.OnNotifyNameChanging(value)
				Me.SendPropertyChanging
				Me._NotifyName = value
				Me.SendPropertyChanged("NotifyName")
				Me.OnNotifyNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CusTitle", DbType:="VarChar(32)")>  _
	Public Property CusTitle() As String
		Get
			Return Me._CusTitle
		End Get
		Set
			If (String.Equals(Me._CusTitle, value) = false) Then
				Me.OnCusTitleChanging(value)
				Me.SendPropertyChanging
				Me._CusTitle = value
				Me.SendPropertyChanged("CusTitle")
				Me.OnCusTitleChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CarGroupID", DbType:="Int")>  _
	Public Property CarGroupID() As System.Nullable(Of Integer)
		Get
			Return Me._CarGroupID
		End Get
		Set
			If (Me._CarGroupID.Equals(value) = false) Then
				Me.OnCarGroupIDChanging(value)
				Me.SendPropertyChanging
				Me._CarGroupID = value
				Me.SendPropertyChanged("CarGroupID")
				Me.OnCarGroupIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CarGroupName", DbType:="VarChar(128)")>  _
	Public Property CarGroupName() As String
		Get
			Return Me._CarGroupName
		End Get
		Set
			If (String.Equals(Me._CarGroupName, value) = false) Then
				Me.OnCarGroupNameChanging(value)
				Me.SendPropertyChanging
				Me._CarGroupName = value
				Me.SendPropertyChanged("CarGroupName")
				Me.OnCarGroupNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CarBrandName", DbType:="VarChar(150)")>  _
	Public Property CarBrandName() As String
		Get
			Return Me._CarBrandName
		End Get
		Set
			If (String.Equals(Me._CarBrandName, value) = false) Then
				Me.OnCarBrandNameChanging(value)
				Me.SendPropertyChanging
				Me._CarBrandName = value
				Me.SendPropertyChanged("CarBrandName")
				Me.OnCarBrandNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CarModelName", DbType:="VarChar(8000)")>  _
	Public Property CarModelName() As String
		Get
			Return Me._CarModelName
		End Get
		Set
			If (String.Equals(Me._CarModelName, value) = false) Then
				Me.OnCarModelNameChanging(value)
				Me.SendPropertyChanging
				Me._CarModelName = value
				Me.SendPropertyChanged("CarModelName")
				Me.OnCarModelNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CarTypeName", DbType:="VarChar(255)")>  _
	Public Property CarTypeName() As String
		Get
			Return Me._CarTypeName
		End Get
		Set
			If (String.Equals(Me._CarTypeName, value) = false) Then
				Me.OnCarTypeNameChanging(value)
				Me.SendPropertyChanging
				Me._CarTypeName = value
				Me.SendPropertyChanged("CarTypeName")
				Me.OnCarTypeNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CarTypeNameFull", DbType:="NVarChar(255)")>  _
	Public Property CarTypeNameFull() As String
		Get
			Return Me._CarTypeNameFull
		End Get
		Set
			If (String.Equals(Me._CarTypeNameFull, value) = false) Then
				Me.OnCarTypeNameFullChanging(value)
				Me.SendPropertyChanging
				Me._CarTypeNameFull = value
				Me.SendPropertyChanged("CarTypeNameFull")
				Me.OnCarTypeNameFullChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CarModelCode", DbType:="VarChar(64)")>  _
	Public Property CarModelCode() As String
		Get
			Return Me._CarModelCode
		End Get
		Set
			If (String.Equals(Me._CarModelCode, value) = false) Then
				Me.OnCarModelCodeChanging(value)
				Me.SendPropertyChanging
				Me._CarModelCode = value
				Me.SendPropertyChanged("CarModelCode")
				Me.OnCarModelCodeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CarGroupNameM2", DbType:="NVarChar(255)")>  _
	Public Property CarGroupNameM2() As String
		Get
			Return Me._CarGroupNameM2
		End Get
		Set
			If (String.Equals(Me._CarGroupNameM2, value) = false) Then
				Me.OnCarGroupNameM2Changing(value)
				Me.SendPropertyChanging
				Me._CarGroupNameM2 = value
				Me.SendPropertyChanged("CarGroupNameM2")
				Me.OnCarGroupNameM2Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DealerNameEn", DbType:="VarChar(100)")>  _
	Public Property DealerNameEn() As String
		Get
			Return Me._DealerNameEn
		End Get
		Set
			If (String.Equals(Me._DealerNameEn, value) = false) Then
				Me.OnDealerNameEnChanging(value)
				Me.SendPropertyChanging
				Me._DealerNameEn = value
				Me.SendPropertyChanged("DealerNameEn")
				Me.OnDealerNameEnChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NLTDealerCode", DbType:="VarChar(50)")>  _
	Public Property NLTDealerCode() As String
		Get
			Return Me._NLTDealerCode
		End Get
		Set
			If (String.Equals(Me._NLTDealerCode, value) = false) Then
				Me.OnNLTDealerCodeChanging(value)
				Me.SendPropertyChanging
				Me._NLTDealerCode = value
				Me.SendPropertyChanged("NLTDealerCode")
				Me.OnNLTDealerCodeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NLTArea", DbType:="VarChar(50)")>  _
	Public Property NLTArea() As String
		Get
			Return Me._NLTArea
		End Get
		Set
			If (String.Equals(Me._NLTArea, value) = false) Then
				Me.OnNLTAreaChanging(value)
				Me.SendPropertyChanging
				Me._NLTArea = value
				Me.SendPropertyChanged("NLTArea")
				Me.OnNLTAreaChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_InsurerNameTh", DbType:="NVarChar(255)")>  _
	Public Property InsurerNameTh() As String
		Get
			Return Me._InsurerNameTh
		End Get
		Set
			If (String.Equals(Me._InsurerNameTh, value) = false) Then
				Me.OnInsurerNameThChanging(value)
				Me.SendPropertyChanging
				Me._InsurerNameTh = value
				Me.SendPropertyChanged("InsurerNameTh")
				Me.OnInsurerNameThChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_InsurerCodeSibis", DbType:="VarChar(50)")>  _
	Public Property InsurerCodeSibis() As String
		Get
			Return Me._InsurerCodeSibis
		End Get
		Set
			If (String.Equals(Me._InsurerCodeSibis, value) = false) Then
				Me.OnInsurerCodeSibisChanging(value)
				Me.SendPropertyChanging
				Me._InsurerCodeSibis = value
				Me.SendPropertyChanged("InsurerCodeSibis")
				Me.OnInsurerCodeSibisChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_InsurerNameEn", DbType:="NVarChar(255)")>  _
	Public Property InsurerNameEn() As String
		Get
			Return Me._InsurerNameEn
		End Get
		Set
			If (String.Equals(Me._InsurerNameEn, value) = false) Then
				Me.OnInsurerNameEnChanging(value)
				Me.SendPropertyChanging
				Me._InsurerNameEn = value
				Me.SendPropertyChanged("InsurerNameEn")
				Me.OnInsurerNameEnChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_InsurerCode", DbType:="VarChar(50)")>  _
	Public Property InsurerCode() As String
		Get
			Return Me._InsurerCode
		End Get
		Set
			If (String.Equals(Me._InsurerCode, value) = false) Then
				Me.OnInsurerCodeChanging(value)
				Me.SendPropertyChanging
				Me._InsurerCode = value
				Me.SendPropertyChanged("InsurerCode")
				Me.OnInsurerCodeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LeasID", DbType:="Int")>  _
	Public Property LeasID() As System.Nullable(Of Integer)
		Get
			Return Me._LeasID
		End Get
		Set
			If (Me._LeasID.Equals(value) = false) Then
				Me.OnLeasIDChanging(value)
				Me.SendPropertyChanging
				Me._LeasID = value
				Me.SendPropertyChanged("LeasID")
				Me.OnLeasIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LeasName", DbType:="NVarChar(100)")>  _
	Public Property LeasName() As String
		Get
			Return Me._LeasName
		End Get
		Set
			If (String.Equals(Me._LeasName, value) = false) Then
				Me.OnLeasNameChanging(value)
				Me.SendPropertyChanging
				Me._LeasName = value
				Me.SendPropertyChanged("LeasName")
				Me.OnLeasNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LeasNameAbbr", DbType:="VarChar(20)")>  _
	Public Property LeasNameAbbr() As String
		Get
			Return Me._LeasNameAbbr
		End Get
		Set
			If (String.Equals(Me._LeasNameAbbr, value) = false) Then
				Me.OnLeasNameAbbrChanging(value)
				Me.SendPropertyChanging
				Me._LeasNameAbbr = value
				Me.SendPropertyChanged("LeasNameAbbr")
				Me.OnLeasNameAbbrChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LeasNameShort", DbType:="VarChar(8) NOT NULL", CanBeNull:=false)>  _
	Public Property LeasNameShort() As String
		Get
			Return Me._LeasNameShort
		End Get
		Set
			If (String.Equals(Me._LeasNameShort, value) = false) Then
				Me.OnLeasNameShortChanging(value)
				Me.SendPropertyChanging
				Me._LeasNameShort = value
				Me.SendPropertyChanged("LeasNameShort")
				Me.OnLeasNameShortChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ModelNameM2", DbType:="NVarChar(255)")>  _
	Public Property ModelNameM2() As String
		Get
			Return Me._ModelNameM2
		End Get
		Set
			If (String.Equals(Me._ModelNameM2, value) = false) Then
				Me.OnModelNameM2Changing(value)
				Me.SendPropertyChanging
				Me._ModelNameM2 = value
				Me.SendPropertyChanged("ModelNameM2")
				Me.OnModelNameM2Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NLTBookingDate", DbType:="DateTime")>  _
	Public Property NLTBookingDate() As System.Nullable(Of Date)
		Get
			Return Me._NLTBookingDate
		End Get
		Set
			If (Me._NLTBookingDate.Equals(value) = false) Then
				Me.OnNLTBookingDateChanging(value)
				Me.SendPropertyChanging
				Me._NLTBookingDate = value
				Me.SendPropertyChanged("NLTBookingDate")
				Me.OnNLTBookingDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SchemeCode", DbType:="NVarChar(50)")>  _
	Public Property SchemeCode() As String
		Get
			Return Me._SchemeCode
		End Get
		Set
			If (String.Equals(Me._SchemeCode, value) = false) Then
				Me.OnSchemeCodeChanging(value)
				Me.SendPropertyChanging
				Me._SchemeCode = value
				Me.SendPropertyChanged("SchemeCode")
				Me.OnSchemeCodeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_VmiNetPremium", DbType:="Decimal(18,2)")>  _
	Public Property VmiNetPremium() As System.Nullable(Of Decimal)
		Get
			Return Me._VmiNetPremium
		End Get
		Set
			If (Me._VmiNetPremium.Equals(value) = false) Then
				Me.OnVmiNetPremiumChanging(value)
				Me.SendPropertyChanging
				Me._VmiNetPremium = value
				Me.SendPropertyChanged("VmiNetPremium")
				Me.OnVmiNetPremiumChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_VmiStamp", DbType:="Decimal(18,2)")>  _
	Public Property VmiStamp() As System.Nullable(Of Decimal)
		Get
			Return Me._VmiStamp
		End Get
		Set
			If (Me._VmiStamp.Equals(value) = false) Then
				Me.OnVmiStampChanging(value)
				Me.SendPropertyChanging
				Me._VmiStamp = value
				Me.SendPropertyChanged("VmiStamp")
				Me.OnVmiStampChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_VmiVat", DbType:="Decimal(18,2)")>  _
	Public Property VmiVat() As System.Nullable(Of Decimal)
		Get
			Return Me._VmiVat
		End Get
		Set
			If (Me._VmiVat.Equals(value) = false) Then
				Me.OnVmiVatChanging(value)
				Me.SendPropertyChanging
				Me._VmiVat = value
				Me.SendPropertyChanged("VmiVat")
				Me.OnVmiVatChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_VmiTotalPremium", DbType:="Decimal(18,2)")>  _
	Public Property VmiTotalPremium() As System.Nullable(Of Decimal)
		Get
			Return Me._VmiTotalPremium
		End Get
		Set
			If (Me._VmiTotalPremium.Equals(value) = false) Then
				Me.OnVmiTotalPremiumChanging(value)
				Me.SendPropertyChanging
				Me._VmiTotalPremium = value
				Me.SendPropertyChanged("VmiTotalPremium")
				Me.OnVmiTotalPremiumChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CmiNetPremium", DbType:="Decimal(18,2)")>  _
	Public Property CmiNetPremium() As System.Nullable(Of Decimal)
		Get
			Return Me._CmiNetPremium
		End Get
		Set
			If (Me._CmiNetPremium.Equals(value) = false) Then
				Me.OnCmiNetPremiumChanging(value)
				Me.SendPropertyChanging
				Me._CmiNetPremium = value
				Me.SendPropertyChanged("CmiNetPremium")
				Me.OnCmiNetPremiumChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CmiStamp", DbType:="Decimal(18,2)")>  _
	Public Property CmiStamp() As System.Nullable(Of Decimal)
		Get
			Return Me._CmiStamp
		End Get
		Set
			If (Me._CmiStamp.Equals(value) = false) Then
				Me.OnCmiStampChanging(value)
				Me.SendPropertyChanging
				Me._CmiStamp = value
				Me.SendPropertyChanged("CmiStamp")
				Me.OnCmiStampChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CmiVat", DbType:="Decimal(18,2)")>  _
	Public Property CmiVat() As System.Nullable(Of Decimal)
		Get
			Return Me._CmiVat
		End Get
		Set
			If (Me._CmiVat.Equals(value) = false) Then
				Me.OnCmiVatChanging(value)
				Me.SendPropertyChanging
				Me._CmiVat = value
				Me.SendPropertyChanged("CmiVat")
				Me.OnCmiVatChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CmiTotalPremium", DbType:="Decimal(18,2)")>  _
	Public Property CmiTotalPremium() As System.Nullable(Of Decimal)
		Get
			Return Me._CmiTotalPremium
		End Get
		Set
			If (Me._CmiTotalPremium.Equals(value) = false) Then
				Me.OnCmiTotalPremiumChanging(value)
				Me.SendPropertyChanging
				Me._CmiTotalPremium = value
				Me.SendPropertyChanged("CmiTotalPremium")
				Me.OnCmiTotalPremiumChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ClassOfRiskVMI", DbType:="Char(8)")>  _
	Public Property ClassOfRiskVMI() As String
		Get
			Return Me._ClassOfRiskVMI
		End Get
		Set
			If (String.Equals(Me._ClassOfRiskVMI, value) = false) Then
				Me.OnClassOfRiskVMIChanging(value)
				Me.SendPropertyChanging
				Me._ClassOfRiskVMI = value
				Me.SendPropertyChanged("ClassOfRiskVMI")
				Me.OnClassOfRiskVMIChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ClassOfRiskCMI", DbType:="Char(8)")>  _
	Public Property ClassOfRiskCMI() As String
		Get
			Return Me._ClassOfRiskCMI
		End Get
		Set
			If (String.Equals(Me._ClassOfRiskCMI, value) = false) Then
				Me.OnClassOfRiskCMIChanging(value)
				Me.SendPropertyChanging
				Me._ClassOfRiskCMI = value
				Me.SendPropertyChanged("ClassOfRiskCMI")
				Me.OnClassOfRiskCMIChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ShowroomID", DbType:="Int")>  _
	Public Property ShowroomID() As System.Nullable(Of Integer)
		Get
			Return Me._ShowroomID
		End Get
		Set
			If (Me._ShowroomID.Equals(value) = false) Then
				Me.OnShowroomIDChanging(value)
				Me.SendPropertyChanging
				Me._ShowroomID = value
				Me.SendPropertyChanged("ShowroomID")
				Me.OnShowroomIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ShowroomName", DbType:="VarChar(150)")>  _
	Public Property ShowroomName() As String
		Get
			Return Me._ShowroomName
		End Get
		Set
			If (String.Equals(Me._ShowroomName, value) = false) Then
				Me.OnShowroomNameChanging(value)
				Me.SendPropertyChanging
				Me._ShowroomName = value
				Me.SendPropertyChanged("ShowroomName")
				Me.OnShowroomNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DealerID", DbType:="Int")>  _
	Public Property DealerID() As System.Nullable(Of Integer)
		Get
			Return Me._DealerID
		End Get
		Set
			If (Me._DealerID.Equals(value) = false) Then
				Me.OnDealerIDChanging(value)
				Me.SendPropertyChanging
				Me._DealerID = value
				Me.SendPropertyChanged("DealerID")
				Me.OnDealerIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ShorwoomNameEn", DbType:="VarChar(100)")>  _
	Public Property ShorwoomNameEn() As String
		Get
			Return Me._ShorwoomNameEn
		End Get
		Set
			If (String.Equals(Me._ShorwoomNameEn, value) = false) Then
				Me.OnShorwoomNameEnChanging(value)
				Me.SendPropertyChanging
				Me._ShorwoomNameEn = value
				Me.SendPropertyChanged("ShorwoomNameEn")
				Me.OnShorwoomNameEnChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CarTypeNameM2", DbType:="NVarChar(50)")>  _
	Public Property CarTypeNameM2() As String
		Get
			Return Me._CarTypeNameM2
		End Get
		Set
			If (String.Equals(Me._CarTypeNameM2, value) = false) Then
				Me.OnCarTypeNameM2Changing(value)
				Me.SendPropertyChanging
				Me._CarTypeNameM2 = value
				Me.SendPropertyChanged("CarTypeNameM2")
				Me.OnCarTypeNameM2Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TypeInsID", DbType:="Int")>  _
	Public Property TypeInsID() As System.Nullable(Of Integer)
		Get
			Return Me._TypeInsID
		End Get
		Set
			If (Me._TypeInsID.Equals(value) = false) Then
				Me.OnTypeInsIDChanging(value)
				Me.SendPropertyChanging
				Me._TypeInsID = value
				Me.SendPropertyChanged("TypeInsID")
				Me.OnTypeInsIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TypeInsName", DbType:="NVarChar(100)")>  _
	Public Property TypeInsName() As String
		Get
			Return Me._TypeInsName
		End Get
		Set
			If (String.Equals(Me._TypeInsName, value) = false) Then
				Me.OnTypeInsNameChanging(value)
				Me.SendPropertyChanging
				Me._TypeInsName = value
				Me.SendPropertyChanged("TypeInsName")
				Me.OnTypeInsNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TypeInsStatus", DbType:="Int")>  _
	Public Property TypeInsStatus() As System.Nullable(Of Integer)
		Get
			Return Me._TypeInsStatus
		End Get
		Set
			If (Me._TypeInsStatus.Equals(value) = false) Then
				Me.OnTypeInsStatusChanging(value)
				Me.SendPropertyChanging
				Me._TypeInsStatus = value
				Me.SendPropertyChanged("TypeInsStatus")
				Me.OnTypeInsStatusChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TypeInsReportToNLTH", DbType:="Bit")>  _
	Public Property TypeInsReportToNLTH() As System.Nullable(Of Boolean)
		Get
			Return Me._TypeInsReportToNLTH
		End Get
		Set
			If (Me._TypeInsReportToNLTH.Equals(value) = false) Then
				Me.OnTypeInsReportToNLTHChanging(value)
				Me.SendPropertyChanging
				Me._TypeInsReportToNLTH = value
				Me.SendPropertyChanged("TypeInsReportToNLTH")
				Me.OnTypeInsReportToNLTHChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TypeInsIsFree", DbType:="Bit")>  _
	Public Property TypeInsIsFree() As System.Nullable(Of Boolean)
		Get
			Return Me._TypeInsIsFree
		End Get
		Set
			If (Me._TypeInsIsFree.Equals(value) = false) Then
				Me.OnTypeInsIsFreeChanging(value)
				Me.SendPropertyChanging
				Me._TypeInsIsFree = value
				Me.SendPropertyChanged("TypeInsIsFree")
				Me.OnTypeInsIsFreeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_UserAddedTel", DbType:="VarChar(64)")>  _
	Public Property UserAddedTel() As String
		Get
			Return Me._UserAddedTel
		End Get
		Set
			If (String.Equals(Me._UserAddedTel, value) = false) Then
				Me.OnUserAddedTelChanging(value)
				Me.SendPropertyChanging
				Me._UserAddedTel = value
				Me.SendPropertyChanged("UserAddedTel")
				Me.OnUserAddedTelChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_UserAddedType", DbType:="VarChar(16)")>  _
	Public Property UserAddedType() As String
		Get
			Return Me._UserAddedType
		End Get
		Set
			If (String.Equals(Me._UserAddedType, value) = false) Then
				Me.OnUserAddedTypeChanging(value)
				Me.SendPropertyChanging
				Me._UserAddedType = value
				Me.SendPropertyChanged("UserAddedType")
				Me.OnUserAddedTypeChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
