'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ucTabs

    '''<summary>
    '''GlobalEvents control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GlobalEvents As Global.DevExpress.Web.ASPxGlobalEvents

    '''<summary>
    '''SqlDataSource_Site control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_Site As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ASPxSplitter1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxSplitter1 As Global.DevExpress.Web.ASPxSplitter

    '''<summary>
    '''SplitterContentControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SplitterContentControl1 As Global.DevExpress.Web.SplitterContentControl

    '''<summary>
    '''tree control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tree As Global.DevExpress.Web.ASPxTreeList.ASPxTreeList

    '''<summary>
    '''cmdEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdEdit As Global.DevExpress.Web.ASPxTreeList.TreeListCommandColumnCustomButton

    '''<summary>
    '''cmdMoveUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdMoveUp As Global.DevExpress.Web.ASPxTreeList.TreeListCommandColumnCustomButton

    '''<summary>
    '''cmdMoveDown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdMoveDown As Global.DevExpress.Web.ASPxTreeList.TreeListCommandColumnCustomButton

    '''<summary>
    '''SplitterContentControl2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SplitterContentControl2 As Global.DevExpress.Web.SplitterContentControl

    '''<summary>
    '''callbackPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents callbackPanel As Global.DevExpress.Web.ASPxCallbackPanel

    '''<summary>
    '''PanelContent1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelContent1 As Global.DevExpress.Web.PanelContent

    '''<summary>
    '''lbTabName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbTabName As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lbAvailable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbAvailable As Global.DevExpress.Web.ASPxListBox

    '''<summary>
    '''btnMoveSelectedItemsToRight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMoveSelectedItemsToRight As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''btnMoveAllItemsToRight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMoveAllItemsToRight As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''btnMoveSelectedItemsToLeft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMoveSelectedItemsToLeft As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''btnMoveAllItemsToLeft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMoveAllItemsToLeft As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''lbChoosen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbChoosen As Global.DevExpress.Web.ASPxListBox

    '''<summary>
    '''btnSaveModule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveModule As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''cbSaveModule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbSaveModule As Global.DevExpress.Web.ASPxCallback

    '''<summary>
    '''SqlDataSource_tabs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_tabs As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_ModuleDefinitions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_ModuleDefinitions As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_Modules control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_Modules As Global.System.Web.UI.WebControls.SqlDataSource
End Class
