'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="LWTReports")>  _
Partial Public Class DataClasses_MCYDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.APDKawa2UWVB.My.MySettings.Default.LWTReportsConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property V_KAWA2_UW_ASIAs() As System.Data.Linq.Table(Of V_KAWA2_UW_ASIA)
		Get
			Return Me.GetTable(Of V_KAWA2_UW_ASIA)
		End Get
	End Property
	
	Public ReadOnly Property V_KAWA2_UW_Non_ASIAs() As System.Data.Linq.Table(Of V_KAWA2_UW_Non_ASIA)
		Get
			Return Me.GetTable(Of V_KAWA2_UW_Non_ASIA)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.V_KAWA2_UW_ASIA")>  _
Partial Public Class V_KAWA2_UW_ASIA
	
	Private _C1 As String
	
	Private _C2 As String
	
	Private _C3 As String
	
	Private _C4 As String
	
	Private _C5 As String
	
	Private _C6 As String
	
	Private _C7 As String
	
	Private _C8 As String
	
	Private _C9 As String
	
	Private _C10 As String
	
	Private _C11 As String
	
	Private _C12 As String
	
	Private _C13 As String
	
	Private _C14 As String
	
	Private _C15 As String
	
	Private _C16 As String
	
	Private _C17 As String
	
	Private _C18 As String
	
	Private _C19 As String
	
	Private _C20 As String
	
	Private _C21 As String
	
	Private _C22 As String
	
	Private _C23 As String
	
	Private _C24 As String
	
	Private _C25 As String
	
	Private _C26 As String
	
	Private _C27 As String
	
	Private _C28 As String
	
	Private _C29 As String
	
	Private _C30 As String
	
	Private _C31 As Integer
	
	Private _C32 As Integer
	
	Private _C33 As System.Nullable(Of Decimal)
	
	Private _C34 As String
	
	Private _C35 As String
	
	Private _C36 As String
	
	Private _C37 As String
	
	Private _C38 As String
	
	Private _C39 As String
	
	Private _C40 As String
	
	Private _C41 As String
	
	Private _C42 As String
	
	Private _C43 As String
	
	Private _C44 As String
	
	Private _C45 As String
	
	Private _C46 As String
	
	Private _C47 As String
	
	Private _C48 As System.Nullable(Of Integer)
	
	Private _C49 As String
	
	Private _C50 As String
	
	Private _C51 As String
	
	Private _C52 As String
	
	Private _C53 As String
	
	Private _C54 As String
	
	Private _C55 As String
	
	Private _C56 As String
	
	Private _C57 As String
	
	Private _C58 As String
	
	Private _C59 As String
	
	Private _C60 As String
	
	Private _C61 As String
	
	Private _C62 As String
	
	Private _C63 As String
	
	Private _C64 As String
	
	Private _C65 As String
	
	Private _C66 As String
	
	Private _C67 As String
	
	Private _C68 As String
	
	Private _C69 As String
	
	Private _C70 As String
	
	Private _C71 As String
	
	Private _C72 As String
	
	Private _C73 As String
	
	Private _C74 As String
	
	Private _C75 As String
	
	Private _C76 As String
	
	Private _C77 As String
	
	Private _C78 As String
	
	Private _C79 As String
	
	Private _C80 As String
	
	Private _C81 As String
	
	Private _C82 As String
	
	Private _C83 As String
	
	Private _C84 As String
	
	Private _C85 As String
	
	Private _C86 As String
	
	Private _C87 As String
	
	Private _C88 As String
	
	Private _C89 As String
	
	Private _C90 As String
	
	Private _C91 As String
	
	Private _C92 As String
	
	Private _C93 As System.Nullable(Of Integer)
	
	Private _C94 As System.Nullable(Of Integer)
	
	Private _C95 As System.Nullable(Of Integer)
	
	Private _C96 As System.Nullable(Of Integer)
	
	Private _C97 As System.Nullable(Of Integer)
	
	Private _C98 As System.Nullable(Of Integer)
	
	Private _C99 As String
	
	Private _C100 As String
	
	Private _C101 As String
	
	Private _C102 As String
	
	Private _C103 As String
	
	Private _C104 As String
	
	Private _C105 As String
	
	Private _C106 As String
	
	Private _C107 As String
	
	Private _C108 As String
	
	Private _C109 As String
	
	Private _C110 As String
	
	Private _C111 As String
	
	Private _C112 As String
	
	Private _C113 As String
	
	Private _C114 As String
	
	Private _C115 As String
	
	Private _C116 As String
	
	Private _C117 As String
	
	Private _C118 As String
	
	Private _C119 As String
	
	Private _C120 As String
	
	Private _C121 As String
	
	Private _C122 As String
	
	Private _C123 As String
	
	Private _C124 As String
	
	Private _C125 As String
	
	Private _C126 As String
	
	Private _C127 As String
	
	Private _C128 As String
	
	Private _C129 As String
	
	Private _C130 As String
	
	Private _C131 As String
	
	Private _C132 As String
	
	Private _C133 As String
	
	Private _C134 As String
	
	Private _C135 As String
	
	Private _C136 As String
	
	Private _C137 As String
	
	Private _C138 As String
	
	Private _C139 As String
	
	Private _C140 As String
	
	Private _C141 As String
	
	Private _C142 As String
	
	Private _C143 As String
	
	Private _C144 As String
	
	Private _C145 As String
	
	Private _C146 As String
	
	Private _C147 As String
	
	Private _C148 As String
	
	Private _C149 As String
	
	Private _C150 As System.Nullable(Of Decimal)
	
	Private _C151 As System.Nullable(Of Decimal)
	
	Private _C152 As System.Nullable(Of Decimal)
	
	Private _C153 As System.Nullable(Of Decimal)
	
	Private _C154 As String
	
	Private _C155 As String
	
	Private _C156 As String
	
	Private _C157 As String
	
	Private _C158 As String
	
	Private _C159 As String
	
	Private _UWCode As String
	
	Private _UWName As String
	
	Private _MailTo As String
	
	Private _MailCC As String
	
	Private _PromotionID As Integer
	
	Private _ProjectID As System.Nullable(Of Integer)
	
	Private _RenewYear As Short
	
	Private _DateMakePolicy As System.Nullable(Of Date)
	
	Private _Renew As Boolean
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C1", DbType:="VarChar(50)")>  _
	Public Property C1() As String
		Get
			Return Me._C1
		End Get
		Set
			If (String.Equals(Me._C1, value) = false) Then
				Me._C1 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C2", DbType:="VarChar(7) NOT NULL", CanBeNull:=false)>  _
	Public Property C2() As String
		Get
			Return Me._C2
		End Get
		Set
			If (String.Equals(Me._C2, value) = false) Then
				Me._C2 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C3", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C3() As String
		Get
			Return Me._C3
		End Get
		Set
			If (String.Equals(Me._C3, value) = false) Then
				Me._C3 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C4", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C4() As String
		Get
			Return Me._C4
		End Get
		Set
			If (String.Equals(Me._C4, value) = false) Then
				Me._C4 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C5", DbType:="Char(8)")>  _
	Public Property C5() As String
		Get
			Return Me._C5
		End Get
		Set
			If (String.Equals(Me._C5, value) = false) Then
				Me._C5 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C6", DbType:="VarChar(50)")>  _
	Public Property C6() As String
		Get
			Return Me._C6
		End Get
		Set
			If (String.Equals(Me._C6, value) = false) Then
				Me._C6 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C7", DbType:="VarChar(201)")>  _
	Public Property C7() As String
		Get
			Return Me._C7
		End Get
		Set
			If (String.Equals(Me._C7, value) = false) Then
				Me._C7 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C8", DbType:="VarChar(100)")>  _
	Public Property C8() As String
		Get
			Return Me._C8
		End Get
		Set
			If (String.Equals(Me._C8, value) = false) Then
				Me._C8 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C9", DbType:="VarChar(250)")>  _
	Public Property C9() As String
		Get
			Return Me._C9
		End Get
		Set
			If (String.Equals(Me._C9, value) = false) Then
				Me._C9 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C10", DbType:="VarChar(64)")>  _
	Public Property C10() As String
		Get
			Return Me._C10
		End Get
		Set
			If (String.Equals(Me._C10, value) = false) Then
				Me._C10 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C11", DbType:="VarChar(64)")>  _
	Public Property C11() As String
		Get
			Return Me._C11
		End Get
		Set
			If (String.Equals(Me._C11, value) = false) Then
				Me._C11 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C12", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C12() As String
		Get
			Return Me._C12
		End Get
		Set
			If (String.Equals(Me._C12, value) = false) Then
				Me._C12 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C13", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C13() As String
		Get
			Return Me._C13
		End Get
		Set
			If (String.Equals(Me._C13, value) = false) Then
				Me._C13 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C14", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C14() As String
		Get
			Return Me._C14
		End Get
		Set
			If (String.Equals(Me._C14, value) = false) Then
				Me._C14 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C15", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C15() As String
		Get
			Return Me._C15
		End Get
		Set
			If (String.Equals(Me._C15, value) = false) Then
				Me._C15 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C16", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C16() As String
		Get
			Return Me._C16
		End Get
		Set
			If (String.Equals(Me._C16, value) = false) Then
				Me._C16 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C17", DbType:="VarChar(100)")>  _
	Public Property C17() As String
		Get
			Return Me._C17
		End Get
		Set
			If (String.Equals(Me._C17, value) = false) Then
				Me._C17 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C18", DbType:="VarChar(100)")>  _
	Public Property C18() As String
		Get
			Return Me._C18
		End Get
		Set
			If (String.Equals(Me._C18, value) = false) Then
				Me._C18 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C19", DbType:="VarChar(50)")>  _
	Public Property C19() As String
		Get
			Return Me._C19
		End Get
		Set
			If (String.Equals(Me._C19, value) = false) Then
				Me._C19 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C20", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C20() As String
		Get
			Return Me._C20
		End Get
		Set
			If (String.Equals(Me._C20, value) = false) Then
				Me._C20 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C21", DbType:="VarChar(10)")>  _
	Public Property C21() As String
		Get
			Return Me._C21
		End Get
		Set
			If (String.Equals(Me._C21, value) = false) Then
				Me._C21 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C22", DbType:="VarChar(10)")>  _
	Public Property C22() As String
		Get
			Return Me._C22
		End Get
		Set
			If (String.Equals(Me._C22, value) = false) Then
				Me._C22 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C23", DbType:="VarChar(10)")>  _
	Public Property C23() As String
		Get
			Return Me._C23
		End Get
		Set
			If (String.Equals(Me._C23, value) = false) Then
				Me._C23 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C24", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C24() As String
		Get
			Return Me._C24
		End Get
		Set
			If (String.Equals(Me._C24, value) = false) Then
				Me._C24 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C25", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C25() As String
		Get
			Return Me._C25
		End Get
		Set
			If (String.Equals(Me._C25, value) = false) Then
				Me._C25 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C26", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C26() As String
		Get
			Return Me._C26
		End Get
		Set
			If (String.Equals(Me._C26, value) = false) Then
				Me._C26 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C27", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C27() As String
		Get
			Return Me._C27
		End Get
		Set
			If (String.Equals(Me._C27, value) = false) Then
				Me._C27 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C28", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C28() As String
		Get
			Return Me._C28
		End Get
		Set
			If (String.Equals(Me._C28, value) = false) Then
				Me._C28 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C29", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C29() As String
		Get
			Return Me._C29
		End Get
		Set
			If (String.Equals(Me._C29, value) = false) Then
				Me._C29 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C30", DbType:="Char(3)")>  _
	Public Property C30() As String
		Get
			Return Me._C30
		End Get
		Set
			If (String.Equals(Me._C30, value) = false) Then
				Me._C30 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C31", DbType:="Int NOT NULL")>  _
	Public Property C31() As Integer
		Get
			Return Me._C31
		End Get
		Set
			If ((Me._C31 = value)  _
						= false) Then
				Me._C31 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C32", DbType:="Int NOT NULL")>  _
	Public Property C32() As Integer
		Get
			Return Me._C32
		End Get
		Set
			If ((Me._C32 = value)  _
						= false) Then
				Me._C32 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C33", DbType:="Decimal(18,2)")>  _
	Public Property C33() As System.Nullable(Of Decimal)
		Get
			Return Me._C33
		End Get
		Set
			If (Me._C33.Equals(value) = false) Then
				Me._C33 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C34", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C34() As String
		Get
			Return Me._C34
		End Get
		Set
			If (String.Equals(Me._C34, value) = false) Then
				Me._C34 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C35", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C35() As String
		Get
			Return Me._C35
		End Get
		Set
			If (String.Equals(Me._C35, value) = false) Then
				Me._C35 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C36", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C36() As String
		Get
			Return Me._C36
		End Get
		Set
			If (String.Equals(Me._C36, value) = false) Then
				Me._C36 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C37", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C37() As String
		Get
			Return Me._C37
		End Get
		Set
			If (String.Equals(Me._C37, value) = false) Then
				Me._C37 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C38", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C38() As String
		Get
			Return Me._C38
		End Get
		Set
			If (String.Equals(Me._C38, value) = false) Then
				Me._C38 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C39", DbType:="VarChar(50)")>  _
	Public Property C39() As String
		Get
			Return Me._C39
		End Get
		Set
			If (String.Equals(Me._C39, value) = false) Then
				Me._C39 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C40", DbType:="VarChar(150)")>  _
	Public Property C40() As String
		Get
			Return Me._C40
		End Get
		Set
			If (String.Equals(Me._C40, value) = false) Then
				Me._C40 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C41", DbType:="VarChar(50)")>  _
	Public Property C41() As String
		Get
			Return Me._C41
		End Get
		Set
			If (String.Equals(Me._C41, value) = false) Then
				Me._C41 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C42", DbType:="VarChar(50)")>  _
	Public Property C42() As String
		Get
			Return Me._C42
		End Get
		Set
			If (String.Equals(Me._C42, value) = false) Then
				Me._C42 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C43", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C43() As String
		Get
			Return Me._C43
		End Get
		Set
			If (String.Equals(Me._C43, value) = false) Then
				Me._C43 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C44", DbType:="VarChar(25)")>  _
	Public Property C44() As String
		Get
			Return Me._C44
		End Get
		Set
			If (String.Equals(Me._C44, value) = false) Then
				Me._C44 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C45", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C45() As String
		Get
			Return Me._C45
		End Get
		Set
			If (String.Equals(Me._C45, value) = false) Then
				Me._C45 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C46", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C46() As String
		Get
			Return Me._C46
		End Get
		Set
			If (String.Equals(Me._C46, value) = false) Then
				Me._C46 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C47", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C47() As String
		Get
			Return Me._C47
		End Get
		Set
			If (String.Equals(Me._C47, value) = false) Then
				Me._C47 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C48", DbType:="Int")>  _
	Public Property C48() As System.Nullable(Of Integer)
		Get
			Return Me._C48
		End Get
		Set
			If (Me._C48.Equals(value) = false) Then
				Me._C48 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C49", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C49() As String
		Get
			Return Me._C49
		End Get
		Set
			If (String.Equals(Me._C49, value) = false) Then
				Me._C49 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C50", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C50() As String
		Get
			Return Me._C50
		End Get
		Set
			If (String.Equals(Me._C50, value) = false) Then
				Me._C50 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C51", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C51() As String
		Get
			Return Me._C51
		End Get
		Set
			If (String.Equals(Me._C51, value) = false) Then
				Me._C51 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C52", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C52() As String
		Get
			Return Me._C52
		End Get
		Set
			If (String.Equals(Me._C52, value) = false) Then
				Me._C52 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C53", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C53() As String
		Get
			Return Me._C53
		End Get
		Set
			If (String.Equals(Me._C53, value) = false) Then
				Me._C53 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C54", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C54() As String
		Get
			Return Me._C54
		End Get
		Set
			If (String.Equals(Me._C54, value) = false) Then
				Me._C54 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C55", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C55() As String
		Get
			Return Me._C55
		End Get
		Set
			If (String.Equals(Me._C55, value) = false) Then
				Me._C55 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C56", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C56() As String
		Get
			Return Me._C56
		End Get
		Set
			If (String.Equals(Me._C56, value) = false) Then
				Me._C56 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C57", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C57() As String
		Get
			Return Me._C57
		End Get
		Set
			If (String.Equals(Me._C57, value) = false) Then
				Me._C57 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C58", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C58() As String
		Get
			Return Me._C58
		End Get
		Set
			If (String.Equals(Me._C58, value) = false) Then
				Me._C58 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C59", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C59() As String
		Get
			Return Me._C59
		End Get
		Set
			If (String.Equals(Me._C59, value) = false) Then
				Me._C59 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C60", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C60() As String
		Get
			Return Me._C60
		End Get
		Set
			If (String.Equals(Me._C60, value) = false) Then
				Me._C60 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C61", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C61() As String
		Get
			Return Me._C61
		End Get
		Set
			If (String.Equals(Me._C61, value) = false) Then
				Me._C61 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C62", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C62() As String
		Get
			Return Me._C62
		End Get
		Set
			If (String.Equals(Me._C62, value) = false) Then
				Me._C62 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C63", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C63() As String
		Get
			Return Me._C63
		End Get
		Set
			If (String.Equals(Me._C63, value) = false) Then
				Me._C63 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C64", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C64() As String
		Get
			Return Me._C64
		End Get
		Set
			If (String.Equals(Me._C64, value) = false) Then
				Me._C64 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C65", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C65() As String
		Get
			Return Me._C65
		End Get
		Set
			If (String.Equals(Me._C65, value) = false) Then
				Me._C65 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C66", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C66() As String
		Get
			Return Me._C66
		End Get
		Set
			If (String.Equals(Me._C66, value) = false) Then
				Me._C66 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C67", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C67() As String
		Get
			Return Me._C67
		End Get
		Set
			If (String.Equals(Me._C67, value) = false) Then
				Me._C67 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C68", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C68() As String
		Get
			Return Me._C68
		End Get
		Set
			If (String.Equals(Me._C68, value) = false) Then
				Me._C68 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C69", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C69() As String
		Get
			Return Me._C69
		End Get
		Set
			If (String.Equals(Me._C69, value) = false) Then
				Me._C69 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C70", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C70() As String
		Get
			Return Me._C70
		End Get
		Set
			If (String.Equals(Me._C70, value) = false) Then
				Me._C70 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C71", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C71() As String
		Get
			Return Me._C71
		End Get
		Set
			If (String.Equals(Me._C71, value) = false) Then
				Me._C71 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C72", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C72() As String
		Get
			Return Me._C72
		End Get
		Set
			If (String.Equals(Me._C72, value) = false) Then
				Me._C72 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C73", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C73() As String
		Get
			Return Me._C73
		End Get
		Set
			If (String.Equals(Me._C73, value) = false) Then
				Me._C73 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C74", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C74() As String
		Get
			Return Me._C74
		End Get
		Set
			If (String.Equals(Me._C74, value) = false) Then
				Me._C74 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C75", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C75() As String
		Get
			Return Me._C75
		End Get
		Set
			If (String.Equals(Me._C75, value) = false) Then
				Me._C75 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C76", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C76() As String
		Get
			Return Me._C76
		End Get
		Set
			If (String.Equals(Me._C76, value) = false) Then
				Me._C76 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C77", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C77() As String
		Get
			Return Me._C77
		End Get
		Set
			If (String.Equals(Me._C77, value) = false) Then
				Me._C77 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C78", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C78() As String
		Get
			Return Me._C78
		End Get
		Set
			If (String.Equals(Me._C78, value) = false) Then
				Me._C78 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C79", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C79() As String
		Get
			Return Me._C79
		End Get
		Set
			If (String.Equals(Me._C79, value) = false) Then
				Me._C79 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C80", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C80() As String
		Get
			Return Me._C80
		End Get
		Set
			If (String.Equals(Me._C80, value) = false) Then
				Me._C80 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C81", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C81() As String
		Get
			Return Me._C81
		End Get
		Set
			If (String.Equals(Me._C81, value) = false) Then
				Me._C81 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C82", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C82() As String
		Get
			Return Me._C82
		End Get
		Set
			If (String.Equals(Me._C82, value) = false) Then
				Me._C82 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C83", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C83() As String
		Get
			Return Me._C83
		End Get
		Set
			If (String.Equals(Me._C83, value) = false) Then
				Me._C83 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C84", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C84() As String
		Get
			Return Me._C84
		End Get
		Set
			If (String.Equals(Me._C84, value) = false) Then
				Me._C84 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C85", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C85() As String
		Get
			Return Me._C85
		End Get
		Set
			If (String.Equals(Me._C85, value) = false) Then
				Me._C85 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C86", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C86() As String
		Get
			Return Me._C86
		End Get
		Set
			If (String.Equals(Me._C86, value) = false) Then
				Me._C86 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C87", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C87() As String
		Get
			Return Me._C87
		End Get
		Set
			If (String.Equals(Me._C87, value) = false) Then
				Me._C87 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C88", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C88() As String
		Get
			Return Me._C88
		End Get
		Set
			If (String.Equals(Me._C88, value) = false) Then
				Me._C88 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C89", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C89() As String
		Get
			Return Me._C89
		End Get
		Set
			If (String.Equals(Me._C89, value) = false) Then
				Me._C89 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C90", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C90() As String
		Get
			Return Me._C90
		End Get
		Set
			If (String.Equals(Me._C90, value) = false) Then
				Me._C90 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C91", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C91() As String
		Get
			Return Me._C91
		End Get
		Set
			If (String.Equals(Me._C91, value) = false) Then
				Me._C91 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C92", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C92() As String
		Get
			Return Me._C92
		End Get
		Set
			If (String.Equals(Me._C92, value) = false) Then
				Me._C92 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C93", DbType:="Int")>  _
	Public Property C93() As System.Nullable(Of Integer)
		Get
			Return Me._C93
		End Get
		Set
			If (Me._C93.Equals(value) = false) Then
				Me._C93 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C94", DbType:="Int")>  _
	Public Property C94() As System.Nullable(Of Integer)
		Get
			Return Me._C94
		End Get
		Set
			If (Me._C94.Equals(value) = false) Then
				Me._C94 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C95", DbType:="Int")>  _
	Public Property C95() As System.Nullable(Of Integer)
		Get
			Return Me._C95
		End Get
		Set
			If (Me._C95.Equals(value) = false) Then
				Me._C95 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C96", DbType:="Int")>  _
	Public Property C96() As System.Nullable(Of Integer)
		Get
			Return Me._C96
		End Get
		Set
			If (Me._C96.Equals(value) = false) Then
				Me._C96 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C97", DbType:="Int")>  _
	Public Property C97() As System.Nullable(Of Integer)
		Get
			Return Me._C97
		End Get
		Set
			If (Me._C97.Equals(value) = false) Then
				Me._C97 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C98", DbType:="Int")>  _
	Public Property C98() As System.Nullable(Of Integer)
		Get
			Return Me._C98
		End Get
		Set
			If (Me._C98.Equals(value) = false) Then
				Me._C98 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C99", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C99() As String
		Get
			Return Me._C99
		End Get
		Set
			If (String.Equals(Me._C99, value) = false) Then
				Me._C99 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C100", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C100() As String
		Get
			Return Me._C100
		End Get
		Set
			If (String.Equals(Me._C100, value) = false) Then
				Me._C100 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C101", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C101() As String
		Get
			Return Me._C101
		End Get
		Set
			If (String.Equals(Me._C101, value) = false) Then
				Me._C101 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C102", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C102() As String
		Get
			Return Me._C102
		End Get
		Set
			If (String.Equals(Me._C102, value) = false) Then
				Me._C102 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C103", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C103() As String
		Get
			Return Me._C103
		End Get
		Set
			If (String.Equals(Me._C103, value) = false) Then
				Me._C103 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C104", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C104() As String
		Get
			Return Me._C104
		End Get
		Set
			If (String.Equals(Me._C104, value) = false) Then
				Me._C104 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C105", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C105() As String
		Get
			Return Me._C105
		End Get
		Set
			If (String.Equals(Me._C105, value) = false) Then
				Me._C105 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C106", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C106() As String
		Get
			Return Me._C106
		End Get
		Set
			If (String.Equals(Me._C106, value) = false) Then
				Me._C106 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C107", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C107() As String
		Get
			Return Me._C107
		End Get
		Set
			If (String.Equals(Me._C107, value) = false) Then
				Me._C107 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C108", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C108() As String
		Get
			Return Me._C108
		End Get
		Set
			If (String.Equals(Me._C108, value) = false) Then
				Me._C108 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C109", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C109() As String
		Get
			Return Me._C109
		End Get
		Set
			If (String.Equals(Me._C109, value) = false) Then
				Me._C109 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C110", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C110() As String
		Get
			Return Me._C110
		End Get
		Set
			If (String.Equals(Me._C110, value) = false) Then
				Me._C110 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C111", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C111() As String
		Get
			Return Me._C111
		End Get
		Set
			If (String.Equals(Me._C111, value) = false) Then
				Me._C111 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C112", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C112() As String
		Get
			Return Me._C112
		End Get
		Set
			If (String.Equals(Me._C112, value) = false) Then
				Me._C112 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C113", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C113() As String
		Get
			Return Me._C113
		End Get
		Set
			If (String.Equals(Me._C113, value) = false) Then
				Me._C113 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C114", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C114() As String
		Get
			Return Me._C114
		End Get
		Set
			If (String.Equals(Me._C114, value) = false) Then
				Me._C114 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C115", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C115() As String
		Get
			Return Me._C115
		End Get
		Set
			If (String.Equals(Me._C115, value) = false) Then
				Me._C115 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C116", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C116() As String
		Get
			Return Me._C116
		End Get
		Set
			If (String.Equals(Me._C116, value) = false) Then
				Me._C116 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C117", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C117() As String
		Get
			Return Me._C117
		End Get
		Set
			If (String.Equals(Me._C117, value) = false) Then
				Me._C117 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C118", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C118() As String
		Get
			Return Me._C118
		End Get
		Set
			If (String.Equals(Me._C118, value) = false) Then
				Me._C118 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C119", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C119() As String
		Get
			Return Me._C119
		End Get
		Set
			If (String.Equals(Me._C119, value) = false) Then
				Me._C119 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C120", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C120() As String
		Get
			Return Me._C120
		End Get
		Set
			If (String.Equals(Me._C120, value) = false) Then
				Me._C120 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C121", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C121() As String
		Get
			Return Me._C121
		End Get
		Set
			If (String.Equals(Me._C121, value) = false) Then
				Me._C121 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C122", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C122() As String
		Get
			Return Me._C122
		End Get
		Set
			If (String.Equals(Me._C122, value) = false) Then
				Me._C122 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C123", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C123() As String
		Get
			Return Me._C123
		End Get
		Set
			If (String.Equals(Me._C123, value) = false) Then
				Me._C123 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C124", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C124() As String
		Get
			Return Me._C124
		End Get
		Set
			If (String.Equals(Me._C124, value) = false) Then
				Me._C124 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C125", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C125() As String
		Get
			Return Me._C125
		End Get
		Set
			If (String.Equals(Me._C125, value) = false) Then
				Me._C125 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C126", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C126() As String
		Get
			Return Me._C126
		End Get
		Set
			If (String.Equals(Me._C126, value) = false) Then
				Me._C126 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C127", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C127() As String
		Get
			Return Me._C127
		End Get
		Set
			If (String.Equals(Me._C127, value) = false) Then
				Me._C127 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C128", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C128() As String
		Get
			Return Me._C128
		End Get
		Set
			If (String.Equals(Me._C128, value) = false) Then
				Me._C128 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C129", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C129() As String
		Get
			Return Me._C129
		End Get
		Set
			If (String.Equals(Me._C129, value) = false) Then
				Me._C129 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C130", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C130() As String
		Get
			Return Me._C130
		End Get
		Set
			If (String.Equals(Me._C130, value) = false) Then
				Me._C130 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C131", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C131() As String
		Get
			Return Me._C131
		End Get
		Set
			If (String.Equals(Me._C131, value) = false) Then
				Me._C131 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C132", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C132() As String
		Get
			Return Me._C132
		End Get
		Set
			If (String.Equals(Me._C132, value) = false) Then
				Me._C132 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C133", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C133() As String
		Get
			Return Me._C133
		End Get
		Set
			If (String.Equals(Me._C133, value) = false) Then
				Me._C133 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C134", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C134() As String
		Get
			Return Me._C134
		End Get
		Set
			If (String.Equals(Me._C134, value) = false) Then
				Me._C134 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C135", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C135() As String
		Get
			Return Me._C135
		End Get
		Set
			If (String.Equals(Me._C135, value) = false) Then
				Me._C135 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C136", DbType:="VarChar(150)")>  _
	Public Property C136() As String
		Get
			Return Me._C136
		End Get
		Set
			If (String.Equals(Me._C136, value) = false) Then
				Me._C136 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C137", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C137() As String
		Get
			Return Me._C137
		End Get
		Set
			If (String.Equals(Me._C137, value) = false) Then
				Me._C137 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C138", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C138() As String
		Get
			Return Me._C138
		End Get
		Set
			If (String.Equals(Me._C138, value) = false) Then
				Me._C138 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C139", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C139() As String
		Get
			Return Me._C139
		End Get
		Set
			If (String.Equals(Me._C139, value) = false) Then
				Me._C139 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C140", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C140() As String
		Get
			Return Me._C140
		End Get
		Set
			If (String.Equals(Me._C140, value) = false) Then
				Me._C140 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C141", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C141() As String
		Get
			Return Me._C141
		End Get
		Set
			If (String.Equals(Me._C141, value) = false) Then
				Me._C141 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C142", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C142() As String
		Get
			Return Me._C142
		End Get
		Set
			If (String.Equals(Me._C142, value) = false) Then
				Me._C142 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C143", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C143() As String
		Get
			Return Me._C143
		End Get
		Set
			If (String.Equals(Me._C143, value) = false) Then
				Me._C143 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C144", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C144() As String
		Get
			Return Me._C144
		End Get
		Set
			If (String.Equals(Me._C144, value) = false) Then
				Me._C144 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C145", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C145() As String
		Get
			Return Me._C145
		End Get
		Set
			If (String.Equals(Me._C145, value) = false) Then
				Me._C145 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C146", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C146() As String
		Get
			Return Me._C146
		End Get
		Set
			If (String.Equals(Me._C146, value) = false) Then
				Me._C146 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C147", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C147() As String
		Get
			Return Me._C147
		End Get
		Set
			If (String.Equals(Me._C147, value) = false) Then
				Me._C147 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C148", DbType:="VarChar(5) NOT NULL", CanBeNull:=false)>  _
	Public Property C148() As String
		Get
			Return Me._C148
		End Get
		Set
			If (String.Equals(Me._C148, value) = false) Then
				Me._C148 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C149", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C149() As String
		Get
			Return Me._C149
		End Get
		Set
			If (String.Equals(Me._C149, value) = false) Then
				Me._C149 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C150", DbType:="Decimal(18,2)")>  _
	Public Property C150() As System.Nullable(Of Decimal)
		Get
			Return Me._C150
		End Get
		Set
			If (Me._C150.Equals(value) = false) Then
				Me._C150 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C151", DbType:="Decimal(10,2)")>  _
	Public Property C151() As System.Nullable(Of Decimal)
		Get
			Return Me._C151
		End Get
		Set
			If (Me._C151.Equals(value) = false) Then
				Me._C151 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C152", DbType:="Decimal(10,2)")>  _
	Public Property C152() As System.Nullable(Of Decimal)
		Get
			Return Me._C152
		End Get
		Set
			If (Me._C152.Equals(value) = false) Then
				Me._C152 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C153", DbType:="Decimal(18,2)")>  _
	Public Property C153() As System.Nullable(Of Decimal)
		Get
			Return Me._C153
		End Get
		Set
			If (Me._C153.Equals(value) = false) Then
				Me._C153 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C154", DbType:="VarChar(25)")>  _
	Public Property C154() As String
		Get
			Return Me._C154
		End Get
		Set
			If (String.Equals(Me._C154, value) = false) Then
				Me._C154 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C155", DbType:="VarChar(250)")>  _
	Public Property C155() As String
		Get
			Return Me._C155
		End Get
		Set
			If (String.Equals(Me._C155, value) = false) Then
				Me._C155 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C156", DbType:="VarChar(50)")>  _
	Public Property C156() As String
		Get
			Return Me._C156
		End Get
		Set
			If (String.Equals(Me._C156, value) = false) Then
				Me._C156 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C157", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C157() As String
		Get
			Return Me._C157
		End Get
		Set
			If (String.Equals(Me._C157, value) = false) Then
				Me._C157 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C158", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C158() As String
		Get
			Return Me._C158
		End Get
		Set
			If (String.Equals(Me._C158, value) = false) Then
				Me._C158 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_C159", DbType:="VarChar(1) NOT NULL", CanBeNull:=false)>  _
	Public Property C159() As String
		Get
			Return Me._C159
		End Get
		Set
			If (String.Equals(Me._C159, value) = false) Then
				Me._C159 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_UWCode", DbType:="VarChar(25) NOT NULL", CanBeNull:=false)>  _
	Public Property UWCode() As String
		Get
			Return Me._UWCode
		End Get
		Set
			If (String.Equals(Me._UWCode, value) = false) Then
				Me._UWCode = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_UWName", DbType:="VarChar(100)")>  _
	Public Property UWName() As String
		Get
			Return Me._UWName
		End Get
		Set
			If (String.Equals(Me._UWName, value) = false) Then
				Me._UWName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MailTo", DbType:="NVarChar(MAX)")>  _
	Public Property MailTo() As String
		Get
			Return Me._MailTo
		End Get
		Set
			If (String.Equals(Me._MailTo, value) = false) Then
				Me._MailTo = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MailCC", DbType:="NVarChar(MAX)")>  _
	Public Property MailCC() As String
		Get
			Return Me._MailCC
		End Get
		Set
			If (String.Equals(Me._MailCC, value) = false) Then
				Me._MailCC = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PromotionID", DbType:="Int NOT NULL")>  _
	Public Property PromotionID() As Integer
		Get
			Return Me._PromotionID
		End Get
		Set
			If ((Me._PromotionID = value)  _
						= false) Then
				Me._PromotionID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ProjectID", DbType:="Int")>  _
	Public Property ProjectID() As System.Nullable(Of Integer)
		Get
			Return Me._ProjectID
		End Get
		Set
			If (Me._ProjectID.Equals(value) = false) Then
				Me._ProjectID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RenewYear", DbType:="SmallInt NOT NULL")>  _
	Public Property RenewYear() As Short
		Get
			Return Me._RenewYear
		End Get
		Set
			If ((Me._RenewYear = value)  _
						= false) Then
				Me._RenewYear = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DateMakePolicy", DbType:="DateTime")>  _
	Public Property DateMakePolicy() As System.Nullable(Of Date)
		Get
			Return Me._DateMakePolicy
		End Get
		Set
			If (Me._DateMakePolicy.Equals(value) = false) Then
				Me._DateMakePolicy = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Renew", DbType:="Bit NOT NULL")>  _
	Public Property Renew() As Boolean
		Get
			Return Me._Renew
		End Get
		Set
			If ((Me._Renew = value)  _
						= false) Then
				Me._Renew = value
			End If
		End Set
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.V_KAWA2_UW_Non_ASIA")>  _
Partial Public Class V_KAWA2_UW_Non_ASIA
	
	Private _Broker_Code As String
	
	Private _PlanCode As String
	
	Private _PlanName As String
	
	Private _UWCode As String
	
	Private _Fleet_Name As String
	
	Private _Introducer_Name As String
	
	Private _Client_Code As String
	
	Private _cTitle As String
	
	Private _Insured_Name As String
	
	Private _ID_Card As String
	
	Private _Insured_s_Address As String
	
	Private _Beneficiary_Name As String
	
	Private _Model As String
	
	Private _License_No As String
	
	Private _Vehicle_Code As String
	
	Private _Year As String
	
	Private _Veh_ChassisNo As String
	
	Private _MVL_Own_Damage As Integer
	
	Private _MVL_Deductible As Integer
	
	Private _MVL_Driver As Integer
	
	Private _MVL_Net_Premium As Decimal
	
	Private _MVL_Stamp As Decimal
	
	Private _MVL_Vat As Decimal
	
	Private _MVL_Total As System.Nullable(Of Decimal)
	
	Private _MVL_Effective As String
	
	Private _MVL_Expire As String
	
	Private _Billing As String
	
	Private _TempPolicyNo As String
	
	Private _PolicyNo As String
	
	Private _DateMakePolicy As System.Nullable(Of Date)
	
	Private _CIDCard As String
	
	Private _ContractNo As String
	
	Private _cPhone As String
	
	Private _Beneficiary As String
	
	Private _TPBIPerPerson As Integer
	
	Private _TPBIPerTime As Integer
	
	Private _TPPD As Integer
	
	Private _BLDriver As Integer
	
	Private _BLPassenger As Integer
	
	Private _MedicalFee As Integer
	
	Private _BailDriver As Integer
	
	Private _RenewYear As Short
	
	Private _UWName As String
	
	Private _MailTo As String
	
	Private _MailCC As String
	
	Private _Renew As Boolean
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Broker_Code", DbType:="VarChar(7) NOT NULL", CanBeNull:=false)>  _
	Public Property Broker_Code() As String
		Get
			Return Me._Broker_Code
		End Get
		Set
			If (String.Equals(Me._Broker_Code, value) = false) Then
				Me._Broker_Code = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PlanCode", DbType:="VarChar(25)")>  _
	Public Property PlanCode() As String
		Get
			Return Me._PlanCode
		End Get
		Set
			If (String.Equals(Me._PlanCode, value) = false) Then
				Me._PlanCode = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PlanName", DbType:="VarChar(100) NOT NULL", CanBeNull:=false)>  _
	Public Property PlanName() As String
		Get
			Return Me._PlanName
		End Get
		Set
			If (String.Equals(Me._PlanName, value) = false) Then
				Me._PlanName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_UWCode", DbType:="VarChar(25) NOT NULL", CanBeNull:=false)>  _
	Public Property UWCode() As String
		Get
			Return Me._UWCode
		End Get
		Set
			If (String.Equals(Me._UWCode, value) = false) Then
				Me._UWCode = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Fleet_Name", DbType:="VarChar(25)")>  _
	Public Property Fleet_Name() As String
		Get
			Return Me._Fleet_Name
		End Get
		Set
			If (String.Equals(Me._Fleet_Name, value) = false) Then
				Me._Fleet_Name = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Introducer_Name", DbType:="VarChar(100)")>  _
	Public Property Introducer_Name() As String
		Get
			Return Me._Introducer_Name
		End Get
		Set
			If (String.Equals(Me._Introducer_Name, value) = false) Then
				Me._Introducer_Name = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[Client Code]", Storage:="_Client_Code", DbType:="Char(8)")>  _
	Public Property Client_Code() As String
		Get
			Return Me._Client_Code
		End Get
		Set
			If (String.Equals(Me._Client_Code, value) = false) Then
				Me._Client_Code = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cTitle", DbType:="VarChar(50)")>  _
	Public Property cTitle() As String
		Get
			Return Me._cTitle
		End Get
		Set
			If (String.Equals(Me._cTitle, value) = false) Then
				Me._cTitle = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[Insured Name]", Storage:="_Insured_Name", DbType:="VarChar(202)")>  _
	Public Property Insured_Name() As String
		Get
			Return Me._Insured_Name
		End Get
		Set
			If (String.Equals(Me._Insured_Name, value) = false) Then
				Me._Insured_Name = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[ID Card]", Storage:="_ID_Card", DbType:="VarChar(50)")>  _
	Public Property ID_Card() As String
		Get
			Return Me._ID_Card
		End Get
		Set
			If (String.Equals(Me._ID_Card, value) = false) Then
				Me._ID_Card = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[Insured's Address]", Storage:="_Insured_s_Address", DbType:="VarChar(1051)")>  _
	Public Property Insured_s_Address() As String
		Get
			Return Me._Insured_s_Address
		End Get
		Set
			If (String.Equals(Me._Insured_s_Address, value) = false) Then
				Me._Insured_s_Address = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Beneficiary_Name", DbType:="VarChar(250)")>  _
	Public Property Beneficiary_Name() As String
		Get
			Return Me._Beneficiary_Name
		End Get
		Set
			If (String.Equals(Me._Beneficiary_Name, value) = false) Then
				Me._Beneficiary_Name = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Model", DbType:="VarChar(32)")>  _
	Public Property Model() As String
		Get
			Return Me._Model
		End Get
		Set
			If (String.Equals(Me._Model, value) = false) Then
				Me._Model = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[License No]", Storage:="_License_No", DbType:="VarChar(50)")>  _
	Public Property License_No() As String
		Get
			Return Me._License_No
		End Get
		Set
			If (String.Equals(Me._License_No, value) = false) Then
				Me._License_No = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[Vehicle Code]", Storage:="_Vehicle_Code", DbType:="Char(3)")>  _
	Public Property Vehicle_Code() As String
		Get
			Return Me._Vehicle_Code
		End Get
		Set
			If (String.Equals(Me._Vehicle_Code, value) = false) Then
				Me._Vehicle_Code = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Year", DbType:="VarChar(25)")>  _
	Public Property Year() As String
		Get
			Return Me._Year
		End Get
		Set
			If (String.Equals(Me._Year, value) = false) Then
				Me._Year = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Veh_ChassisNo", DbType:="VarChar(50)")>  _
	Public Property Veh_ChassisNo() As String
		Get
			Return Me._Veh_ChassisNo
		End Get
		Set
			If (String.Equals(Me._Veh_ChassisNo, value) = false) Then
				Me._Veh_ChassisNo = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[MVL Own Damage]", Storage:="_MVL_Own_Damage", DbType:="Int NOT NULL")>  _
	Public Property MVL_Own_Damage() As Integer
		Get
			Return Me._MVL_Own_Damage
		End Get
		Set
			If ((Me._MVL_Own_Damage = value)  _
						= false) Then
				Me._MVL_Own_Damage = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[MVL Deductible]", Storage:="_MVL_Deductible", DbType:="Int NOT NULL")>  _
	Public Property MVL_Deductible() As Integer
		Get
			Return Me._MVL_Deductible
		End Get
		Set
			If ((Me._MVL_Deductible = value)  _
						= false) Then
				Me._MVL_Deductible = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[MVL Driver]", Storage:="_MVL_Driver", DbType:="Int NOT NULL")>  _
	Public Property MVL_Driver() As Integer
		Get
			Return Me._MVL_Driver
		End Get
		Set
			If ((Me._MVL_Driver = value)  _
						= false) Then
				Me._MVL_Driver = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[MVL Net Premium]", Storage:="_MVL_Net_Premium", DbType:="Decimal(18,2) NOT NULL")>  _
	Public Property MVL_Net_Premium() As Decimal
		Get
			Return Me._MVL_Net_Premium
		End Get
		Set
			If ((Me._MVL_Net_Premium = value)  _
						= false) Then
				Me._MVL_Net_Premium = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[MVL Stamp]", Storage:="_MVL_Stamp", DbType:="Decimal(10,2) NOT NULL")>  _
	Public Property MVL_Stamp() As Decimal
		Get
			Return Me._MVL_Stamp
		End Get
		Set
			If ((Me._MVL_Stamp = value)  _
						= false) Then
				Me._MVL_Stamp = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[MVL Vat]", Storage:="_MVL_Vat", DbType:="Decimal(10,2) NOT NULL")>  _
	Public Property MVL_Vat() As Decimal
		Get
			Return Me._MVL_Vat
		End Get
		Set
			If ((Me._MVL_Vat = value)  _
						= false) Then
				Me._MVL_Vat = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[MVL Total]", Storage:="_MVL_Total", DbType:="Decimal(18,2)")>  _
	Public Property MVL_Total() As System.Nullable(Of Decimal)
		Get
			Return Me._MVL_Total
		End Get
		Set
			If (Me._MVL_Total.Equals(value) = false) Then
				Me._MVL_Total = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[MVL Effective]", Storage:="_MVL_Effective", DbType:="VarChar(10)")>  _
	Public Property MVL_Effective() As String
		Get
			Return Me._MVL_Effective
		End Get
		Set
			If (String.Equals(Me._MVL_Effective, value) = false) Then
				Me._MVL_Effective = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[MVL Expire]", Storage:="_MVL_Expire", DbType:="VarChar(10)")>  _
	Public Property MVL_Expire() As String
		Get
			Return Me._MVL_Expire
		End Get
		Set
			If (String.Equals(Me._MVL_Expire, value) = false) Then
				Me._MVL_Expire = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Billing", DbType:="VarChar(402)")>  _
	Public Property Billing() As String
		Get
			Return Me._Billing
		End Get
		Set
			If (String.Equals(Me._Billing, value) = false) Then
				Me._Billing = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TempPolicyNo", DbType:="VarChar(50)")>  _
	Public Property TempPolicyNo() As String
		Get
			Return Me._TempPolicyNo
		End Get
		Set
			If (String.Equals(Me._TempPolicyNo, value) = false) Then
				Me._TempPolicyNo = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PolicyNo", DbType:="VarChar(50)")>  _
	Public Property PolicyNo() As String
		Get
			Return Me._PolicyNo
		End Get
		Set
			If (String.Equals(Me._PolicyNo, value) = false) Then
				Me._PolicyNo = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DateMakePolicy", DbType:="DateTime")>  _
	Public Property DateMakePolicy() As System.Nullable(Of Date)
		Get
			Return Me._DateMakePolicy
		End Get
		Set
			If (Me._DateMakePolicy.Equals(value) = false) Then
				Me._DateMakePolicy = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CIDCard", DbType:="VarChar(50)")>  _
	Public Property CIDCard() As String
		Get
			Return Me._CIDCard
		End Get
		Set
			If (String.Equals(Me._CIDCard, value) = false) Then
				Me._CIDCard = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ContractNo", DbType:="VarChar(50)")>  _
	Public Property ContractNo() As String
		Get
			Return Me._ContractNo
		End Get
		Set
			If (String.Equals(Me._ContractNo, value) = false) Then
				Me._ContractNo = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cPhone", DbType:="VarChar(100)")>  _
	Public Property cPhone() As String
		Get
			Return Me._cPhone
		End Get
		Set
			If (String.Equals(Me._cPhone, value) = false) Then
				Me._cPhone = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Beneficiary", DbType:="VarChar(250)")>  _
	Public Property Beneficiary() As String
		Get
			Return Me._Beneficiary
		End Get
		Set
			If (String.Equals(Me._Beneficiary, value) = false) Then
				Me._Beneficiary = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TPBIPerPerson", DbType:="Int NOT NULL")>  _
	Public Property TPBIPerPerson() As Integer
		Get
			Return Me._TPBIPerPerson
		End Get
		Set
			If ((Me._TPBIPerPerson = value)  _
						= false) Then
				Me._TPBIPerPerson = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TPBIPerTime", DbType:="Int NOT NULL")>  _
	Public Property TPBIPerTime() As Integer
		Get
			Return Me._TPBIPerTime
		End Get
		Set
			If ((Me._TPBIPerTime = value)  _
						= false) Then
				Me._TPBIPerTime = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TPPD", DbType:="Int NOT NULL")>  _
	Public Property TPPD() As Integer
		Get
			Return Me._TPPD
		End Get
		Set
			If ((Me._TPPD = value)  _
						= false) Then
				Me._TPPD = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_BLDriver", DbType:="Int NOT NULL")>  _
	Public Property BLDriver() As Integer
		Get
			Return Me._BLDriver
		End Get
		Set
			If ((Me._BLDriver = value)  _
						= false) Then
				Me._BLDriver = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_BLPassenger", DbType:="Int NOT NULL")>  _
	Public Property BLPassenger() As Integer
		Get
			Return Me._BLPassenger
		End Get
		Set
			If ((Me._BLPassenger = value)  _
						= false) Then
				Me._BLPassenger = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MedicalFee", DbType:="Int NOT NULL")>  _
	Public Property MedicalFee() As Integer
		Get
			Return Me._MedicalFee
		End Get
		Set
			If ((Me._MedicalFee = value)  _
						= false) Then
				Me._MedicalFee = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_BailDriver", DbType:="Int NOT NULL")>  _
	Public Property BailDriver() As Integer
		Get
			Return Me._BailDriver
		End Get
		Set
			If ((Me._BailDriver = value)  _
						= false) Then
				Me._BailDriver = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RenewYear", DbType:="SmallInt NOT NULL")>  _
	Public Property RenewYear() As Short
		Get
			Return Me._RenewYear
		End Get
		Set
			If ((Me._RenewYear = value)  _
						= false) Then
				Me._RenewYear = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_UWName", DbType:="VarChar(100)")>  _
	Public Property UWName() As String
		Get
			Return Me._UWName
		End Get
		Set
			If (String.Equals(Me._UWName, value) = false) Then
				Me._UWName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MailTo", DbType:="NVarChar(MAX)")>  _
	Public Property MailTo() As String
		Get
			Return Me._MailTo
		End Get
		Set
			If (String.Equals(Me._MailTo, value) = false) Then
				Me._MailTo = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MailCC", DbType:="NVarChar(MAX)")>  _
	Public Property MailCC() As String
		Get
			Return Me._MailCC
		End Get
		Set
			If (String.Equals(Me._MailCC, value) = false) Then
				Me._MailCC = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Renew", DbType:="Bit NOT NULL")>  _
	Public Property Renew() As Boolean
		Get
			Return Me._Renew
		End Get
		Set
			If ((Me._Renew = value)  _
						= false) Then
				Me._Renew = value
			End If
		End Set
	End Property
End Class
